// sprite-gen/src/main.rs
//
// Reads ASCII art sprite component files (body, tail variants, leg variants)
// and generates firmware/src/cat_sprites.rs with pre-assembled const frames.

use std::fs;
use std::path::Path;

const TAIL_ROWS: usize = 14;
const BODY_ROWS: usize = 27;
const LEGS_ROWS: usize = 15;
const TOTAL_ROWS: usize = TAIL_ROWS + BODY_ROWS + LEGS_ROWS; // 56
const COLS: usize = 56;

/// Parse an ASCII art file into a Vec of u64.
/// '#' = on (bit set), '.' = off (bit clear).
/// Bit 55 = leftmost column, bit 0 = rightmost column.
fn parse_art(content: &str) -> Vec<u64> {
    content
        .lines()
        .filter(|line| !line.is_empty())
        .map(|line| {
            let mut row: u64 = 0;
            for (col, ch) in line.chars().enumerate() {
                if col >= COLS {
                    break;
                }
                if ch == '#' {
                    row |= 1u64 << (COLS - 1 - col);
                }
            }
            row
        })
        .collect()
}

fn assemble_frame(tail: &[u64], body: &[u64], legs: &[u64]) -> [u64; TOTAL_ROWS] {
    assert_eq!(tail.len(), TAIL_ROWS, "tail must be {TAIL_ROWS} rows");
    assert_eq!(body.len(), BODY_ROWS, "body must be {BODY_ROWS} rows");
    assert_eq!(legs.len(), LEGS_ROWS, "legs must be {LEGS_ROWS} rows");

    let mut frame = [0u64; TOTAL_ROWS];
    frame[..TAIL_ROWS].copy_from_slice(tail);
    frame[TAIL_ROWS..TAIL_ROWS + BODY_ROWS].copy_from_slice(body);
    frame[TAIL_ROWS + BODY_ROWS..].copy_from_slice(legs);
    frame
}

fn generate_rust(frames: &[[u64; TOTAL_ROWS]]) -> String {
    let mut out = String::new();
    out.push_str("/// Auto-generated by sprite-gen. Do not edit by hand.\n");
    out.push_str("/// Source: docs/sprites/{body,tail-*,legs-*}.txt\n\n");
    out.push_str(&format!("pub const FRAME_ROWS: usize = {TOTAL_ROWS};\n"));
    out.push_str(&format!("pub const FRAME_COLS: usize = {COLS};\n"));
    out.push_str(&format!(
        "pub const FRAME_COUNT: usize = {};\n\n",
        frames.len()
    ));
    out.push_str("/// Frames 0-3: tail up + 4 leg poses.\n");
    out.push_str("/// Frames 4-7: tail down + 4 leg poses.\n");
    out.push_str("pub const FRAMES: [[u64; FRAME_ROWS]; FRAME_COUNT] = [\n");

    for (i, frame) in frames.iter().enumerate() {
        out.push_str(&format!("    [ // frame {i}\n"));
        for row in frame {
            out.push_str(&format!("        0x{row:014X},\n"));
        }
        out.push_str("    ],\n");
    }

    out.push_str("];\n");
    out
}

fn main() {
    let sprites_dir = Path::new("docs/sprites");
    let output_path = Path::new("firmware/src/cat_sprites.rs");

    let body = parse_art(
        &fs::read_to_string(sprites_dir.join("body.txt")).expect("failed to read body.txt"),
    );
    let tail_up = parse_art(
        &fs::read_to_string(sprites_dir.join("tail-up.txt")).expect("failed to read tail-up.txt"),
    );
    let tail_down = parse_art(
        &fs::read_to_string(sprites_dir.join("tail-down.txt"))
            .expect("failed to read tail-down.txt"),
    );

    let legs: Vec<Vec<u64>> = (1..=4)
        .map(|i| {
            let path = sprites_dir.join(format!("legs-stride-{i}.txt"));
            parse_art(
                &fs::read_to_string(&path)
                    .unwrap_or_else(|_| panic!("failed to read {}", path.display())),
            )
        })
        .collect();

    let tails = [&tail_up, &tail_down];
    let mut frames = Vec::new();
    for tail in &tails {
        for leg in &legs {
            frames.push(assemble_frame(tail, &body, leg));
        }
    }

    let rust_code = generate_rust(&frames);
    fs::write(output_path, &rust_code).expect("failed to write cat_sprites.rs");

    println!(
        "Generated {} with {} frames ({TOTAL_ROWS} rows each)",
        output_path.display(),
        frames.len()
    );
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_parse_art_simple() {
        let art = "#..#\n.##.\n";
        let rows = parse_art(art);
        assert_eq!(rows.len(), 2);
        // col 0 = '#' -> bit 55, col 3 = '#' -> bit 52
        assert_eq!(rows[0], (1u64 << 55) | (1u64 << 52));
        // col 1 = '#' -> bit 54, col 2 = '#' -> bit 53
        assert_eq!(rows[1], (1u64 << 54) | (1u64 << 53));
    }

    #[test]
    fn test_parse_art_full_row() {
        let art = &"#".repeat(56);
        let rows = parse_art(art);
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0], (1u64 << 56) - 1);
    }

    #[test]
    fn test_parse_art_empty_row() {
        let art = &".".repeat(56);
        let rows = parse_art(art);
        assert_eq!(rows.len(), 1);
        assert_eq!(rows[0], 0);
    }

    #[test]
    fn test_parse_art_skips_blank_lines() {
        let art = "#...\n\n.#..\n";
        let rows = parse_art(art);
        assert_eq!(rows.len(), 2);
    }

    #[test]
    fn test_assemble_frame() {
        let tail = vec![1u64; TAIL_ROWS];
        let body = vec![2u64; BODY_ROWS];
        let legs = vec![3u64; LEGS_ROWS];
        let frame = assemble_frame(&tail, &body, &legs);
        assert_eq!(frame.len(), TOTAL_ROWS);
        assert!(frame[..TAIL_ROWS].iter().all(|&r| r == 1));
        assert!(frame[TAIL_ROWS..TAIL_ROWS + BODY_ROWS].iter().all(|&r| r == 2));
        assert!(frame[TAIL_ROWS + BODY_ROWS..].iter().all(|&r| r == 3));
    }

    #[test]
    fn test_generate_rust_format() {
        let frames = vec![[0u64; TOTAL_ROWS]; 2];
        let code = generate_rust(&frames);
        assert!(code.contains("pub const FRAME_ROWS: usize = 56;"));
        assert!(code.contains("pub const FRAME_COLS: usize = 56;"));
        assert!(code.contains("pub const FRAME_COUNT: usize = 2;"));
        assert!(code.contains("pub const FRAMES:"));
        assert!(code.contains("0x00000000000000,"));
    }
}
