//! Power-on self-test (POST): validate the on-device crypto against known-answer
//! vectors at boot, before the device is trusted with a real key.
//!
//! This is the cheapest hardware-bring-up insurance. If the lx106's unaligned
//! access silently corrupts k256 (the open Phase-0 risk), `pubkey`/`sign` return
//! wrong bytes and the POST fails loudly on the OLED — instead of the failure
//! hiding for hours as "the relays keep rejecting my events". A k256 *hard* fault
//! shows up as the POST never reaching OK (the device hangs in the self-test).
//!
//! The vectors are computed on the host with the same k256 (see
//! `scratchpad/signtest`); the device recomputes and compares.

use crate::crypto;
use heartwood_common::nip44;

// Generated by scratchpad/signtest for selftest.rs (k256 0.13).
const TEST_SEED: [u8; 32] = [0x11; 32];
const TEST_MSG: [u8; 32] = [0xab; 32];
const EXPECTED_PUBKEY: [u8; 32] = [
    0x4f, 0x35, 0x5b, 0xdc, 0xb7, 0xcc, 0x0a, 0xf7, 0x28, 0xef, 0x3c, 0xce, 0xb9, 0x61, 0x5d, 0x90,
    0x68, 0x4b, 0xb5, 0xb2, 0xca, 0x5f, 0x85, 0x9a, 0xb0, 0xf0, 0xb7, 0x04, 0x07, 0x58, 0x71, 0xaa,
];
const EXPECTED_SIG: [u8; 64] = [
    0xba, 0xe2, 0x62, 0xd8, 0xf2, 0xcc, 0x4f, 0x2d, 0x57, 0x69, 0xda, 0xba, 0x78, 0xca, 0xf5, 0x02,
    0x30, 0x22, 0x08, 0x16, 0x07, 0xfb, 0x05, 0x86, 0x02, 0xd3, 0x5d, 0x72, 0x4b, 0xda, 0xb1, 0xa6,
    0xf3, 0x3f, 0xf9, 0x83, 0x3c, 0x7c, 0x03, 0xde, 0x26, 0x8c, 0x6f, 0x7b, 0x2c, 0x0d, 0xa0, 0x4e,
    0x0f, 0x70, 0x63, 0xd6, 0x86, 0x66, 0xe5, 0x12, 0x9f, 0x94, 0xd4, 0xd5, 0xdd, 0x26, 0x1b, 0xf8,
];

/// Run the boot self-test. `Ok(())` if every check passes, else a short name for
/// the first failing one (shown on the OLED).
pub fn run() -> Result<(), &'static str> {
    // 1. k256 public-key derivation (EC point multiplication) — the operation
    //    most exposed to the unaligned-access risk.
    let pk = crypto::pubkey(&TEST_SEED).ok_or("pubkey: none")?;
    if pk != EXPECTED_PUBKEY {
        return Err("pubkey mismatch");
    }

    // 2. BIP-340 deterministic signing — must match the host byte-for-byte.
    let sig = crypto::sign(&TEST_SEED, &TEST_MSG).ok_or("sign: none")?;
    if sig != EXPECTED_SIG {
        return Err("sign mismatch");
    }

    // 3. NIP-44 ECDH + AEAD round-trip (encrypt then decrypt). Exercises the
    //    conversation-key ECDH, ChaCha20, HKDF and HMAC paths.
    let ck = nip44::get_conversation_key(&TEST_SEED, &EXPECTED_PUBKEY).map_err(|_| "nip44 ck")?;
    let nonce = [0x24u8; 32];
    let ct = nip44::encrypt(&ck, "heartwood-post", &nonce).map_err(|_| "nip44 enc")?;
    let pt = nip44::decrypt(&ck, &ct).map_err(|_| "nip44 dec")?;
    if pt != "heartwood-post" {
        return Err("nip44 roundtrip");
    }

    Ok(())
}
