//! Network configuration for WiFi-standalone mode.
//! Pure, host-testable. Stored as a JSON blob in NVS by the firmware.
#[allow(unused_imports)]
use alloc::{
    format,
    string::{String, ToString},
    vec,
    vec::Vec,
};

#[cfg(feature = "nip46")]
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum DeviceMode {
    Usb,
    Wifi,
}

/// Coarse, privacy-safe progress through the device's outbound network path.
///
/// This is intentionally operational rather than identifying: it never carries
/// an IP address, MAC address, SSID, relay URL, public key, or raw error text.
/// Firmware may expose it alongside the existing redacted USB network config so
/// a locally attached owner can distinguish "saved" from "actually online".
#[cfg(feature = "nip46")]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NetworkRuntimeStage {
    RadioOff,
    Starting,
    WifiConnecting,
    WifiReady,
    RelayConnecting,
    SubscriptionSent,
    Online,
    ConfigError,
}

/// Sanitized failure class for local connectivity diagnostics.
///
/// The classes are deliberately broad. In particular, WiFi authentication,
/// range, and DHCP failures are not separated because ESP-IDF cannot reliably
/// distinguish a wrong password from a lost handshake, and raw driver/TLS
/// errors can reveal more network detail than this diagnostic needs.
#[cfg(feature = "nip46")]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NetworkRuntimeError {
    None,
    WifiUnavailable,
    RelayTransport,
    WebsocketUpgrade,
    RelayProtocol,
    RelayClosed,
    RelaySilent,
    InvalidConfig,
}

/// Additive runtime portion of `GET_NET_CONFIG`.
///
/// All fields are booleans or closed enums so future callers cannot
/// accidentally surface a network identifier through this type.
#[cfg(feature = "nip46")]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
pub struct NetworkRuntimeStatus {
    pub stage: NetworkRuntimeStage,
    pub wifi_connected: bool,
    pub relay_connected: bool,
    pub last_error_class: NetworkRuntimeError,
}

#[cfg(feature = "nip46")]
impl NetworkRuntimeStatus {
    pub const fn radio_off() -> Self {
        Self {
            stage: NetworkRuntimeStage::RadioOff,
            wifi_connected: false,
            relay_connected: false,
            last_error_class: NetworkRuntimeError::None,
        }
    }

    pub const fn starting() -> Self {
        Self {
            stage: NetworkRuntimeStage::Starting,
            wifi_connected: false,
            relay_connected: false,
            last_error_class: NetworkRuntimeError::None,
        }
    }
}

#[cfg(feature = "nip46")]
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NetConfig {
    pub ssid: String,
    pub password: String,
    #[serde(default)]
    pub relays: Vec<String>,
    pub mode: String, // "usb" | "wifi"
    /// Hex-encoded operator pubkey (`op_mgmt`) authorised to manage this device
    /// over relays (kind 24134). Empty/absent → relay management disabled.
    /// Generated by Sapwood at flash time; the operator holds the matching nsec.
    #[serde(default)]
    pub op_mgmt: String,
}

#[cfg(feature = "nip46")]
impl core::fmt::Debug for NetConfig {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("NetConfig")
            .field("ssid", &self.ssid)
            .field(
                "password",
                &if self.password.is_empty() {
                    "<empty>"
                } else {
                    "<set>"
                },
            )
            .field("relays", &self.relays)
            .field("mode", &self.mode)
            .field("op_mgmt", &self.op_mgmt)
            .finish()
    }
}

/// Authenticated relay-management patch for a staged network trial.
///
/// This deliberately does not contain `op_mgmt`: the key that authorises the
/// request cannot be replaced by the request itself. Unknown fields are
/// rejected so a newer/misspelled client cannot accidentally get a partial
/// configuration applied by older firmware.
#[cfg(feature = "nip46")]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(deny_unknown_fields)]
pub struct RemoteNetConfigPatch {
    #[serde(default)]
    pub mode: Option<String>,
    #[serde(default)]
    pub ssid: Option<String>,
    #[serde(default)]
    pub relays: Option<Vec<String>>,
    #[serde(default)]
    pub password: Option<RemotePasswordPatch>,
}

/// Physical-USB network patch. It has the same keep/set/clear password
/// semantics as remote staging, but may also switch to the radio-off tier. The
/// firmware accepts this type only on the cable and only after local button
/// confirmation. Management trust-root rotation uses its own narrower frame.
#[cfg(feature = "nip46")]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, Default)]
#[serde(deny_unknown_fields)]
pub struct LocalNetConfigPatch {
    #[serde(default)]
    pub mode: Option<String>,
    #[serde(default)]
    pub ssid: Option<String>,
    #[serde(default)]
    pub relays: Option<Vec<String>>,
    #[serde(default)]
    pub password: Option<RemotePasswordPatch>,
}

#[cfg(feature = "nip46")]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct LocalNetConfigPatchParams {
    pub base_revision: u32,
    pub patch: LocalNetConfigPatch,
}

#[cfg(feature = "nip46")]
#[derive(Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct RemotePasswordPatch {
    pub action: String,
    #[serde(default)]
    pub value: Option<String>,
}

#[cfg(feature = "nip46")]
impl core::fmt::Debug for RemotePasswordPatch {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        f.debug_struct("RemotePasswordPatch")
            .field("action", &self.action)
            .field(
                "value",
                &self.value.as_ref().map(|_| "<redacted>"),
            )
            .finish()
    }
}

#[cfg(feature = "nip46")]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct StageNetworkConfigParams {
    pub base_revision: u32,
    pub transaction_id: String,
    pub patch: RemoteNetConfigPatch,
}

#[cfg(feature = "nip46")]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(deny_unknown_fields)]
pub struct NetworkConfigTransactionParams {
    pub transaction_id: String,
    pub revision: u32,
}

#[cfg(feature = "nip46")]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NetworkTrialPhase {
    Staged,
    Trying,
    Committed,
}

/// Versioned single-blob representation of a remote network transaction. NVS
/// replacement of one blob is atomic, avoiding torn candidate/id/attempt keys.
#[cfg(feature = "nip46")]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NetworkTrialRecord {
    pub version: u8,
    pub transaction_id: String,
    pub accepted_revision: u32,
    pub candidate: NetConfig,
    pub phase: NetworkTrialPhase,
    pub attempts: u8,
}

#[cfg(feature = "nip46")]
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum NetworkTrialBootAction {
    UseActive,
    TryCandidate,
    RollBack,
    FinalizeCommitted,
}

#[cfg(feature = "nip46")]
#[derive(Debug, Clone, Copy, PartialEq, Eq, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum NetworkTerminalOutcome {
    Committed,
    RolledBack,
    Aborted,
}

#[cfg(feature = "nip46")]
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct NetworkTerminalRecord {
    pub version: u8,
    pub transaction_id: String,
    pub revision: u32,
    pub outcome: NetworkTerminalOutcome,
}

/// Pure boot decision used by firmware before it mutates the persisted record.
/// STAGED is inert, TRYING gets exactly one candidate boot, and a second boot
/// rolls back without ever selecting the candidate again.
#[cfg(feature = "nip46")]
pub fn network_trial_boot_action(record: &NetworkTrialRecord) -> NetworkTrialBootAction {
    match (record.phase, record.attempts) {
        (NetworkTrialPhase::Staged, _) => NetworkTrialBootAction::UseActive,
        (NetworkTrialPhase::Trying, 0) => NetworkTrialBootAction::TryCandidate,
        (NetworkTrialPhase::Trying, _) => NetworkTrialBootAction::RollBack,
        (NetworkTrialPhase::Committed, _) => NetworkTrialBootAction::FinalizeCommitted,
    }
}

/// A network trial may be committed only through one of its configured relay
/// rotations. A client-pinned relay is never an acceptable proof that the new
/// network path works, even if it happens to use the same URL.
#[cfg(feature = "nip46")]
pub fn network_commit_source_allowed(
    session_is_pinned: bool,
    session_url: &str,
    candidate_relays: &[String],
) -> bool {
    if session_is_pinned {
        return false;
    }
    let session = session_url.trim().trim_end_matches('/');
    candidate_relays.iter().any(|relay| {
        relay
            .trim()
            .trim_end_matches('/')
            .eq_ignore_ascii_case(session)
    })
}

/// Activation schedules a delayed reboot after its response is published. The
/// delivering relay must have bounded reads so the outer loop can reach that
/// deadline instead of blocking forever on the next quiet socket read.
#[cfg(feature = "nip46")]
pub fn network_activation_source_allowed(recv_timeout_on: bool) -> bool {
    recv_timeout_on
}

#[cfg(feature = "nip46")]
pub fn valid_network_transaction_id(transaction_id: &str) -> bool {
    transaction_id.len() == 32 && transaction_id.bytes().all(|b| b.is_ascii_hexdigit())
}

#[cfg(feature = "nip46")]
pub fn network_revision_matches(requested: u32, current: u32) -> bool {
    requested == current
}

#[cfg(feature = "nip46")]
pub fn effective_network_revision(
    stored: u32,
    pending: Option<u32>,
    terminal: Option<u32>,
) -> u32 {
    stored.max(pending.unwrap_or(0)).max(terminal.unwrap_or(0))
}

/// Build the exact STAGED record persisted before the monotonic revision write.
#[cfg(feature = "nip46")]
pub fn new_network_trial_record(
    transaction_id: String,
    accepted_revision: u32,
    candidate: NetConfig,
) -> NetworkTrialRecord {
    NetworkTrialRecord {
        version: 1,
        transaction_id,
        accepted_revision,
        candidate,
        phase: NetworkTrialPhase::Staged,
        attempts: 0,
    }
}

/// Pure STAGED -> TRYING transition used by firmware before replacing the
/// transaction blob. Repeating activation before the reboot is idempotent.
#[cfg(feature = "nip46")]
pub fn activate_network_trial_record(
    record: &NetworkTrialRecord,
    transaction_id: &str,
    revision: u32,
) -> Result<NetworkTrialRecord, &'static str> {
    if record.transaction_id != transaction_id {
        return Err("network transaction id mismatch");
    }
    if !network_revision_matches(revision, record.accepted_revision) {
        return Err("network transaction revision mismatch");
    }
    match record.phase {
        NetworkTrialPhase::Staged => {
            let mut trying = record.clone();
            trying.phase = NetworkTrialPhase::Trying;
            trying.attempts = 0;
            Ok(trying)
        }
        NetworkTrialPhase::Trying if record.attempts == 0 => Ok(record.clone()),
        NetworkTrialPhase::Trying => Err("network trial is already active"),
        NetworkTrialPhase::Committed => Err("network transaction is already committed"),
    }
}

/// Persisted immediately before the one allowed candidate boot is selected.
#[cfg(feature = "nip46")]
pub fn mark_network_trial_attempt(
    record: &NetworkTrialRecord,
) -> Result<NetworkTrialRecord, &'static str> {
    if record.phase != NetworkTrialPhase::Trying || record.attempts != 0 {
        return Err("network trial cannot start another attempt");
    }
    let mut attempted = record.clone();
    attempted.attempts = 1;
    Ok(attempted)
}

/// Atomic commit decision. Firmware persists this Committed record before
/// promoting the active config; every later boot therefore selects candidate B.
#[cfg(feature = "nip46")]
pub fn commit_network_trial_record(
    record: &NetworkTrialRecord,
    transaction_id: &str,
    revision: u32,
) -> Result<NetworkTrialRecord, &'static str> {
    if record.transaction_id != transaction_id {
        return Err("network transaction id mismatch");
    }
    if !network_revision_matches(revision, record.accepted_revision) {
        return Err("network transaction revision mismatch");
    }
    if record.phase != NetworkTrialPhase::Trying || record.attempts != 1 {
        return Err("network trial has not booted");
    }
    let mut committed = record.clone();
    committed.phase = NetworkTrialPhase::Committed;
    Ok(committed)
}

#[cfg(feature = "nip46")]
impl NetConfig {
    pub fn device_mode(&self) -> DeviceMode {
        match self.mode.as_str() {
            "wifi" => DeviceMode::Wifi,
            _ => DeviceMode::Usb,
        }
    }

    /// The operator management pubkey (32 bytes) if configured and valid hex.
    /// `None` disables the relay management channel (kind 24134).
    pub fn op_mgmt_pubkey(&self) -> Option<[u8; 32]> {
        crate::hex::hex_decode(&self.op_mgmt).ok()?.try_into().ok()
    }

    /// WiFi mode requires an SSID and at least one relay; USB mode is always valid.
    pub fn validate(&self) -> Result<(), &'static str> {
        if self.device_mode() == DeviceMode::Wifi {
            if self.ssid.is_empty() {
                return Err("ssid required for wifi mode");
            }
            if self.relays.is_empty() {
                return Err("at least one relay required for wifi mode");
            }
        }
        Ok(())
    }
}

/// Apply a remote patch to the active configuration without changing its
/// management trust root. The result is suitable only as a one-shot WiFi
/// trial; remote management can never turn the radio off.
#[cfg(feature = "nip46")]
pub fn apply_remote_net_config_patch(
    active: &NetConfig,
    patch: &RemoteNetConfigPatch,
) -> Result<NetConfig, &'static str> {
    if patch.mode.is_none()
        && patch.ssid.is_none()
        && patch.relays.is_none()
        && patch.password.is_none()
    {
        return Err("network patch is empty");
    }

    if let Some(mode) = patch.mode.as_deref() {
        if mode != "wifi" {
            return Err("remote network mode must be wifi");
        }
    }

    let mut candidate = active.clone();
    candidate.mode = "wifi".to_string();
    if let Some(ssid) = &patch.ssid {
        candidate.ssid = ssid.clone();
    }
    if let Some(relays) = &patch.relays {
        candidate.relays = relays.clone();
    }
    let ssid_changed = candidate.ssid != active.ssid;
    if let Some(password) = &patch.password {
        match password.action.as_str() {
            "keep" => {
                if password.value.is_some() {
                    return Err("password keep must not include value");
                }
                if ssid_changed {
                    return Err("changing ssid requires password set or clear");
                }
            }
            "clear" => {
                if password.value.is_some() {
                    return Err("password clear must not include value");
                }
                candidate.password.clear();
            }
            "set" => {
                candidate.password = password
                    .value
                    .clone()
                    .ok_or("password set requires value")?;
            }
            _ => return Err("password action must be keep, set, or clear"),
        }
    } else if ssid_changed {
        return Err("changing ssid requires password set or clear");
    }

    // `op_mgmt` is copied from `active` above and is intentionally never
    // writable through RemoteNetConfigPatch.
    validate_remote_net_config(&candidate)?;
    Ok(candidate)
}

/// Apply a physically confirmed USB patch without requiring the host to read
/// or resend the stored WiFi password. Unlike the remote patch, local custody
/// may select USB-only mode. It cannot change `op_mgmt`.
#[cfg(feature = "nip46")]
pub fn apply_local_net_config_patch(
    active: &NetConfig,
    patch: &LocalNetConfigPatch,
) -> Result<NetConfig, &'static str> {
    if patch.mode.is_none()
        && patch.ssid.is_none()
        && patch.relays.is_none()
        && patch.password.is_none()
    {
        return Err("network patch is empty");
    }

    if let Some(mode) = patch.mode.as_deref() {
        if mode != "wifi" && mode != "usb" {
            return Err("local network mode must be wifi or usb");
        }
    }

    let mut candidate = active.clone();
    if let Some(mode) = &patch.mode {
        candidate.mode = mode.clone();
    }
    if let Some(ssid) = &patch.ssid {
        candidate.ssid = ssid.clone();
    }
    if let Some(relays) = &patch.relays {
        candidate.relays = relays.clone();
    }
    let ssid_changed = candidate.ssid != active.ssid;
    if let Some(password) = &patch.password {
        match password.action.as_str() {
            "keep" => {
                if password.value.is_some() {
                    return Err("password keep must not include value");
                }
                if ssid_changed {
                    return Err("changing ssid requires password set or clear");
                }
            }
            "clear" => {
                if password.value.is_some() {
                    return Err("password clear must not include value");
                }
                candidate.password.clear();
            }
            "set" => {
                candidate.password = password
                    .value
                    .clone()
                    .ok_or("password set requires value")?;
            }
            _ => return Err("password action must be keep, set, or clear"),
        }
    } else if ssid_changed {
        return Err("changing ssid requires password set or clear");
    }

    // A WiFi candidate will be consumed by fixed-capacity ESP-IDF fields, so
    // apply the same strict bounds as remote staging. USB-only mode keeps the
    // dormant network values for later recovery and still validates its trust
    // root above.
    if candidate.device_mode() == DeviceMode::Wifi {
        validate_remote_net_config(&candidate)?;
    }
    Ok(candidate)
}

/// Strict validation for a remotely staged WiFi candidate. It is stronger
/// than the legacy USB validator because a malformed remote candidate must
/// never reach `heapless::String::try_into().expect()` during boot.
#[cfg(feature = "nip46")]
pub fn validate_remote_net_config(cfg: &NetConfig) -> Result<(), &'static str> {
    if cfg.mode != "wifi" {
        return Err("remote network mode must be wifi");
    }
    if cfg.ssid.is_empty() || cfg.ssid.len() > 32 {
        return Err("ssid must be 1-32 bytes");
    }
    if cfg.ssid.bytes().any(|b| b == 0 || b.is_ascii_control()) {
        return Err("ssid contains control characters");
    }
    let password_len = cfg.password.len();
    let valid_raw_psk = password_len == 64 && cfg.password.bytes().all(|b| b.is_ascii_hexdigit());
    if password_len != 0 && !(8..=63).contains(&password_len) && !valid_raw_psk {
        return Err("password must be empty, 8-63 bytes, or a 64-character hex PSK");
    }
    if cfg.password.bytes().any(|b| b == 0 || b.is_ascii_control()) {
        return Err("password contains control characters");
    }
    if cfg.relays.is_empty() || cfg.relays.len() > 8 {
        return Err("one to eight relays required");
    }
    for (index, relay) in cfg.relays.iter().enumerate() {
        if !relay.starts_with("wss://") || relay.len() > 255 {
            return Err("relay must be a wss:// URL no longer than 255 bytes");
        }
        let authority = relay[6..]
            .split(|c| c == '/' || c == '?' || c == '#')
            .next()
            .unwrap_or("");
        let host = authority.split(':').next().unwrap_or("");
        if authority.contains('@')
            || host.is_empty()
            || !host.bytes().any(|b| b.is_ascii_alphanumeric())
            || !host
                .bytes()
                .all(|b| b.is_ascii_alphanumeric() || b == b'.' || b == b'-')
        {
            return Err("relay URL requires a nonempty host");
        }
        let port = &authority[host.len()..];
        if !port.is_empty() && port != ":443" {
            return Err("relay URL port must be 443");
        }
        let suffix = &relay[6 + authority.len()..];
        if !suffix.is_empty() && suffix != "/" {
            return Err("relay URL path, query, and fragment are not supported");
        }
        if relay
            .bytes()
            .any(|b| b.is_ascii_whitespace() || b.is_ascii_control())
        {
            return Err("relay URL contains whitespace or control characters");
        }
        if cfg.relays[..index].iter().any(|existing| {
            existing
                .trim_end_matches('/')
                .eq_ignore_ascii_case(relay.trim_end_matches('/'))
        }) {
            return Err("duplicate relay URL");
        }
    }
    Ok(())
}

#[cfg(feature = "nip46")]
pub fn parse_net_config(bytes: &[u8]) -> Result<NetConfig, &'static str> {
    serde_json::from_slice(bytes).map_err(|_| "invalid net config json")
}

#[cfg(all(test, feature = "nip46"))]
mod tests {
    use super::*;

    #[test]
    fn parses_wifi_config() {
        let json = br#"{"ssid":"home","password":"secret","relays":["wss://relay.example"],"mode":"wifi"}"#;
        let cfg = parse_net_config(json).unwrap();
        assert_eq!(cfg.ssid, "home");
        assert_eq!(cfg.device_mode(), DeviceMode::Wifi);
        assert_eq!(cfg.relays, vec!["wss://relay.example".to_string()]);
        cfg.validate().unwrap();
    }

    #[test]
    fn runtime_status_serialization_is_closed_and_identifier_free() {
        let status = NetworkRuntimeStatus {
            stage: NetworkRuntimeStage::RelayConnecting,
            wifi_connected: true,
            relay_connected: false,
            last_error_class: NetworkRuntimeError::WebsocketUpgrade,
        };
        let value = serde_json::to_value(status).unwrap();
        assert_eq!(
            value,
            serde_json::json!({
                "stage": "relay_connecting",
                "wifi_connected": true,
                "relay_connected": false,
                "last_error_class": "websocket_upgrade",
            })
        );
        let keys = value
            .as_object()
            .unwrap()
            .keys()
            .cloned()
            .collect::<Vec<_>>();
        assert_eq!(
            keys,
            vec![
                "last_error_class",
                "relay_connected",
                "stage",
                "wifi_connected"
            ]
        );
    }

    #[test]
    fn wifi_without_relays_is_invalid() {
        let json = br#"{"ssid":"home","password":"x","relays":[],"mode":"wifi"}"#;
        let cfg = parse_net_config(json).unwrap();
        assert!(cfg.validate().is_err());
    }

    #[test]
    fn wifi_without_ssid_is_invalid() {
        let json = br#"{"ssid":"","password":"x","relays":["wss://r"],"mode":"wifi"}"#;
        let cfg = parse_net_config(json).unwrap();
        assert!(cfg.validate().is_err());
    }

    #[test]
    fn usb_mode_defaults_ok() {
        let json = br#"{"ssid":"","password":"","relays":[],"mode":"usb"}"#;
        let cfg = parse_net_config(json).unwrap();
        assert_eq!(cfg.device_mode(), DeviceMode::Usb);
        cfg.validate().unwrap();
    }

    #[test]
    fn rejects_garbage() {
        assert!(parse_net_config(b"not json").is_err());
    }

    fn active() -> NetConfig {
        NetConfig {
            ssid: "old-network".to_string(),
            password: "old-password".to_string(),
            relays: vec!["wss://old.example".to_string()],
            mode: "wifi".to_string(),
            op_mgmt: "11".repeat(32),
        }
    }

    #[test]
    fn remote_patch_preserves_operator_and_keeps_password() {
        let active = active();
        let patch: RemoteNetConfigPatch = serde_json::from_str(
            r#"{"relays":["wss://new.example"],"password":{"action":"keep"}}"#,
        )
        .unwrap();
        let candidate = apply_remote_net_config_patch(&active, &patch).unwrap();
        assert_eq!(candidate.ssid, "old-network");
        assert_eq!(candidate.password, "old-password");
        assert_eq!(candidate.op_mgmt, active.op_mgmt);
        assert_eq!(candidate.mode, "wifi");
    }

    #[test]
    fn remote_patch_can_set_or_clear_password() {
        let active = active();
        let set: RemoteNetConfigPatch =
            serde_json::from_str(r#"{"password":{"action":"set","value":"new-password"}}"#)
                .unwrap();
        assert_eq!(
            apply_remote_net_config_patch(&active, &set)
                .unwrap()
                .password,
            "new-password"
        );

        let clear: RemoteNetConfigPatch =
            serde_json::from_str(r#"{"password":{"action":"clear"}}"#).unwrap();
        assert_eq!(
            apply_remote_net_config_patch(&active, &clear)
                .unwrap()
                .password,
            ""
        );
    }

    #[test]
    fn local_patch_keeps_password_and_operator_when_editing_relays() {
        let active = active();
        let patch: LocalNetConfigPatch = serde_json::from_str(
            r#"{"relays":["wss://new.example"],"password":{"action":"keep"}}"#,
        )
        .unwrap();
        let candidate = apply_local_net_config_patch(&active, &patch).unwrap();
        assert_eq!(candidate.password, "old-password");
        assert_eq!(candidate.op_mgmt, active.op_mgmt);
        assert_eq!(candidate.relays, vec!["wss://new.example".to_string()]);
    }

    #[test]
    fn local_patch_params_require_revision_and_exact_fields() {
        assert!(serde_json::from_str::<LocalNetConfigPatchParams>(
            r#"{"base_revision":7,"patch":{"mode":"usb"}}"#
        )
        .is_ok());
        assert!(serde_json::from_str::<LocalNetConfigPatchParams>(
            r#"{"patch":{"mode":"usb"}}"#
        )
        .is_err());
        assert!(serde_json::from_str::<LocalNetConfigPatchParams>(
            r#"{"base_revision":7,"patch":{"mode":"usb"},"extra":true}"#
        )
        .is_err());
    }

    #[test]
    fn local_patch_can_select_usb_only_without_rotating_operator() {
        let active = active();
        let radio_off: LocalNetConfigPatch =
            serde_json::from_str(r#"{"mode":"usb"}"#).unwrap();
        let candidate = apply_local_net_config_patch(&active, &radio_off).unwrap();
        assert_eq!(candidate.device_mode(), DeviceMode::Usb);
        assert_eq!(candidate.password, active.password);
        assert_eq!(candidate.op_mgmt, active.op_mgmt);
    }

    #[test]
    fn local_patch_rejects_implicit_password_reuse_and_operator_field() {
        let changed_ssid: LocalNetConfigPatch =
            serde_json::from_str(r#"{"ssid":"different"}"#).unwrap();
        assert_eq!(
            apply_local_net_config_patch(&active(), &changed_ssid),
            Err("changing ssid requires password set or clear")
        );

        assert!(serde_json::from_str::<LocalNetConfigPatch>(
            &format!(r#"{{"op_mgmt":"{}"}}"#, "22".repeat(32))
        )
        .is_err());
        assert!(serde_json::from_str::<LocalNetConfigPatch>(r#"{"typo":true}"#).is_err());
    }

    #[test]
    fn changing_ssid_requires_explicit_password_decision() {
        let implicit: RemoteNetConfigPatch =
            serde_json::from_str(r#"{"ssid":"new-network"}"#).unwrap();
        assert_eq!(
            apply_remote_net_config_patch(&active(), &implicit),
            Err("changing ssid requires password set or clear")
        );
        let keep: RemoteNetConfigPatch =
            serde_json::from_str(r#"{"ssid":"new-network","password":{"action":"keep"}}"#).unwrap();
        assert_eq!(
            apply_remote_net_config_patch(&active(), &keep),
            Err("changing ssid requires password set or clear")
        );
    }

    #[test]
    fn remote_patch_rejects_usb_operator_and_unknown_fields() {
        let usb: RemoteNetConfigPatch = serde_json::from_str(r#"{"mode":"usb"}"#).unwrap();
        assert_eq!(
            apply_remote_net_config_patch(&active(), &usb),
            Err("remote network mode must be wifi")
        );
        assert!(serde_json::from_str::<RemoteNetConfigPatch>(r#"{"op_mgmt":"attacker"}"#).is_err());
        assert!(serde_json::from_str::<RemoteNetConfigPatch>(r#"{"ssid":"x","typo":1}"#).is_err());
    }

    #[test]
    fn remote_patch_rejects_unsafe_lengths_and_relays() {
        let long_ssid = RemoteNetConfigPatch {
            ssid: Some("x".repeat(33)),
            ..Default::default()
        };
        assert!(apply_remote_net_config_patch(&active(), &long_ssid).is_err());

        let short_password: RemoteNetConfigPatch =
            serde_json::from_str(r#"{"password":{"action":"set","value":"short"}}"#).unwrap();
        assert!(apply_remote_net_config_patch(&active(), &short_password).is_err());

        let insecure_relay: RemoteNetConfigPatch =
            serde_json::from_str(r#"{"relays":["ws://relay.example"]}"#).unwrap();
        assert!(apply_remote_net_config_patch(&active(), &insecure_relay).is_err());
    }

    #[test]
    fn password_action_is_strict() {
        let extra_value: RemoteNetConfigPatch =
            serde_json::from_str(r#"{"password":{"action":"keep","value":"not-used"}}"#).unwrap();
        assert!(apply_remote_net_config_patch(&active(), &extra_value).is_err());
        assert!(serde_json::from_str::<RemotePasswordPatch>(
            r#"{"action":"clear","unexpected":true}"#
        )
        .is_err());
    }

    #[test]
    fn staged_trial_is_inert_and_trying_trial_is_one_shot() {
        let mut record = NetworkTrialRecord {
            version: 1,
            transaction_id: "01".repeat(16),
            accepted_revision: 7,
            candidate: active(),
            phase: NetworkTrialPhase::Staged,
            attempts: 0,
        };
        assert_eq!(
            network_trial_boot_action(&record),
            NetworkTrialBootAction::UseActive
        );
        record.phase = NetworkTrialPhase::Trying;
        assert_eq!(
            network_trial_boot_action(&record),
            NetworkTrialBootAction::TryCandidate
        );
        record.attempts = 1;
        assert_eq!(
            network_trial_boot_action(&record),
            NetworkTrialBootAction::RollBack
        );
        record.phase = NetworkTrialPhase::Committed;
        assert_eq!(
            network_trial_boot_action(&record),
            NetworkTrialBootAction::FinalizeCommitted
        );
    }

    #[test]
    fn power_cut_model_preserves_stage_attempt_commit_and_rollback_boundaries() {
        let transaction_id = "01".repeat(16);
        let candidate = active();
        let staged = new_network_trial_record(transaction_id.clone(), 7, candidate.clone());
        let staged: NetworkTrialRecord =
            serde_json::from_slice(&serde_json::to_vec(&staged).unwrap()).unwrap();

        // Cut after the atomic trial blob but before net_rev: pending N+1 is
        // still the effective revision, and a merely STAGED boot stays on A.
        assert_eq!(effective_network_revision(6, Some(7), None), 7);
        assert_eq!(
            network_trial_boot_action(&staged),
            NetworkTrialBootAction::UseActive
        );

        assert!(activate_network_trial_record(&staged, &transaction_id, 6).is_err());
        assert!(activate_network_trial_record(&staged, &"02".repeat(16), 7).is_err());
        let trying = activate_network_trial_record(&staged, &transaction_id, 7).unwrap();
        assert_eq!(
            network_trial_boot_action(&trying),
            NetworkTrialBootAction::TryCandidate
        );
        assert_eq!(
            activate_network_trial_record(&trying, &transaction_id, 7).unwrap(),
            trying
        );

        // The attempted marker is written before B is selected. A cut before
        // the Committed marker therefore rolls back, never retries B.
        let attempted = mark_network_trial_attempt(&trying).unwrap();
        let attempted: NetworkTrialRecord =
            serde_json::from_slice(&serde_json::to_vec(&attempted).unwrap()).unwrap();
        assert_eq!(attempted.attempts, 1);
        assert_eq!(
            network_trial_boot_action(&attempted),
            NetworkTrialBootAction::RollBack
        );
        assert!(mark_network_trial_attempt(&attempted).is_err());
        assert!(commit_network_trial_record(&trying, &transaction_id, 7).is_err());

        // Once the single-blob Committed marker exists, every boot finalises B,
        // even if active-config or terminal-result cleanup lost power.
        let committed =
            commit_network_trial_record(&attempted, &transaction_id, 7).unwrap();
        let committed: NetworkTrialRecord =
            serde_json::from_slice(&serde_json::to_vec(&committed).unwrap()).unwrap();
        assert_eq!(committed.candidate, candidate);
        assert_eq!(
            network_trial_boot_action(&committed),
            NetworkTrialBootAction::FinalizeCommitted
        );
        assert!(commit_network_trial_record(&attempted, &transaction_id, 8).is_err());

        // Cut after terminal N+1 but before/without net_rev cannot regress the
        // monotonic revision after the pending record is cleaned up.
        assert_eq!(effective_network_revision(6, None, Some(7)), 7);
    }

    #[test]
    fn commit_source_must_be_candidate_primary_not_pinned() {
        let relays = vec!["wss://candidate.example/".to_string()];
        assert!(network_commit_source_allowed(
            false,
            "WSS://CANDIDATE.EXAMPLE",
            &relays
        ));
        assert!(!network_commit_source_allowed(
            true,
            "wss://candidate.example",
            &relays
        ));
        assert!(!network_commit_source_allowed(
            false,
            "wss://unrelated.example",
            &relays
        ));
    }

    #[test]
    fn activation_requires_bounded_relay_reads() {
        assert!(network_activation_source_allowed(true));
        assert!(!network_activation_source_allowed(false));
    }

    #[test]
    fn transaction_id_is_exactly_128_bit_hex() {
        assert!(valid_network_transaction_id("0123456789abcdef0123456789ABCDEF"));
        assert!(!valid_network_transaction_id(""));
        assert!(!valid_network_transaction_id("0123456789abcdef0123456789abcde"));
        assert!(!valid_network_transaction_id("0123456789abcdef0123456789abcdef00"));
        assert!(!valid_network_transaction_id("0123456789abcdef0123456789abcdeg"));
    }

    #[test]
    fn debug_output_redacts_password() {
        let rendered = format!("{:?}", active());
        assert!(rendered.contains("<set>"));
        assert!(!rendered.contains("old-password"));
        let patch: RemoteNetConfigPatch = serde_json::from_str(
            r#"{"password":{"action":"set","value":"new-password"}}"#,
        )
        .unwrap();
        let rendered_patch = format!("{:?}", patch);
        assert!(rendered_patch.contains("<redacted>"));
        assert!(!rendered_patch.contains("new-password"));
    }

    #[test]
    fn transaction_steps_require_exact_revision() {
        assert!(network_revision_matches(7, 7));
        assert!(!network_revision_matches(6, 7));
        assert!(serde_json::from_str::<NetworkConfigTransactionParams>(
            r#"{"transaction_id":"0123456789abcdef0123456789abcdef","revision":7}"#
        )
        .is_ok());
        assert!(serde_json::from_str::<NetworkConfigTransactionParams>(
            r#"{"transaction_id":"0123456789abcdef0123456789abcdef"}"#
        )
        .is_err());
        assert_eq!(effective_network_revision(6, Some(7), None), 7);
        assert_eq!(effective_network_revision(6, None, Some(7)), 7);
        assert_eq!(effective_network_revision(8, Some(7), Some(6)), 8);
    }
}
