// common/src/policy.rs
//
// Client approval policy types shared between firmware and bridge.
#[allow(unused_imports)]
use alloc::{
    format,
    string::{String, ToString},
    vec,
    vec::Vec,
};

use serde::{Deserialize, Serialize};

/// Maximum connection slots per master.
pub const MAX_CONNECT_SLOTS: u8 = 16;

/// Maximum client pubkeys retained per slot. A slot's secret is a shared
/// credential, so every device that pairs with it is remembered and stays
/// auto-approved. Beyond this cap the oldest entry is dropped (FIFO). Keep
/// this modest: the persisted blob for all 16 slots must fit the NVS read
/// buffer in the firmware's `load_from_nvs`.
pub const MAX_AUTHORIZED_PUBKEYS: usize = 8;

/// A named connection slot for a specific master.
///
/// Each slot has its own bunker URI secret. The slot -- not the ephemeral
/// client pubkey -- is the stable identity. Every client that connects with
/// the slot secret is remembered in `authorized_pubkeys` and stays auto-approved;
/// clients are never evicted by a later pairing, so multiple devices sharing one
/// slot (e.g. signet-app on a phone plus a desktop) all sign without prompting.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConnectSlot {
    /// Slot index (0-15).
    pub slot_index: u8,
    /// Human-readable label (e.g. "nostrudel desktop").
    pub label: String,
    /// Hex-encoded 32-byte secret (64 chars). Generated by hardware RNG.
    pub secret: String,
    /// Hex-encoded most-recently-connected client pubkey. Always also present
    /// in `authorized_pubkeys`; kept separately for display ("who's active").
    #[serde(default)]
    pub current_pubkey: Option<String>,
    /// Which NIP-46 methods are auto-approved for this slot.
    /// Empty means no policy-controlled method is auto-approved.
    #[serde(default)]
    pub allowed_methods: Vec<String>,
    /// Which event kinds are auto-approved for sign_event.
    #[serde(default)]
    pub allowed_kinds: Vec<u64>,
    /// Whether to auto-approve matching requests (true) or just OLED-notify (false).
    #[serde(default)]
    pub auto_approve: bool,
    /// True once the user has physically approved a sign_event via button press.
    #[serde(default)]
    pub signing_approved: bool,
    /// When true, methods and event kinds outside this slot's policy are denied
    /// instead of falling back to a physical button prompt. New remotely-managed
    /// v2 slots set this; legacy slots default false to preserve first-sign TOFU.
    #[serde(default)]
    pub strict_permissions: bool,
    /// Every client pubkey that has paired with this slot's secret. All are
    /// auto-approvable (subject to the slot's other gates). Capped at
    /// `MAX_AUTHORIZED_PUBKEYS`. Old NVS blobs without this field deserialise
    /// to an empty vec; `current_pubkey` still matches via [`slot_authorizes`],
    /// so an already-bound client keeps working until it next re-pairs.
    #[serde(default)]
    pub authorized_pubkeys: Vec<String>,
}

/// A client's approval policy for a specific master.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClientPolicy {
    /// Hex-encoded client public key (64 chars).
    pub client_pubkey: String,
    /// Human-readable label (e.g. "Bark browser").
    #[serde(default)]
    pub label: String,
    /// Which NIP-46 methods are auto-approved.
    /// Empty means no policy-controlled method is auto-approved.
    #[serde(default)]
    pub allowed_methods: Vec<String>,
    /// Which event kinds are auto-approved for sign_event.
    /// Empty = all kinds allowed.
    #[serde(default)]
    pub allowed_kinds: Vec<u64>,
    /// Whether to auto-approve matching requests (true) or just OLED-notify (false).
    #[serde(default)]
    pub auto_approve: bool,
}

/// Methods auto-approved on connect when the client provides a valid secret.
/// These are non-signing operations -- safe to grant without physical approval.
pub const CONNECT_SAFE_METHODS: &[&str] = &[
    "nip44_encrypt",
    "nip44_decrypt",
    "nip04_encrypt",
    "nip04_decrypt",
    "get_public_key",
];

/// Methods auto-approved after first physical button approval.
/// Includes signing -- only granted after the user explicitly approves once.
pub const TOFU_SAFE_METHODS: &[&str] = &[
    "sign_event",
    "nip44_encrypt",
    "nip44_decrypt",
    "nip04_encrypt",
    "nip04_decrypt",
    "get_public_key",
];

/// Bound exact remotely-managed policies so an authenticated but buggy manager
/// cannot grow the persisted NVS blob without limit.
pub const MAX_ALLOWED_KINDS: usize = 64;

/// A validated, exact auto-approval policy supplied by the authenticated
/// operator. `signing_approved` is deliberately not supplied independently: it
/// is derived from whether `sign_event` is present, so the two gates cannot
/// drift into an accidentally broader state.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExactSlotPolicy {
    pub allowed_methods: Vec<String>,
    pub allowed_kinds: Vec<u64>,
    pub auto_approve: bool,
    pub signing_approved: bool,
}

/// Validate and canonicalise an exact operator policy before any slot state is
/// mutated. Only methods implemented by Heartwood's standard NIP-46 handler are
/// accepted. Event kinds are meaningful only when `sign_event` is present.
pub fn validate_exact_slot_policy(
    allowed_methods: Vec<String>,
    allowed_kinds: Vec<u64>,
    auto_approve: bool,
) -> Result<ExactSlotPolicy, &'static str> {
    let mut methods = Vec::new();
    for method in allowed_methods {
        if !TOFU_SAFE_METHODS.contains(&method.as_str()) {
            return Err("policy contains an unsupported method");
        }
        if !methods.iter().any(|existing| existing == &method) {
            methods.push(method);
        }
    }

    if allowed_kinds.len() > MAX_ALLOWED_KINDS {
        return Err("policy contains too many event kinds");
    }
    let mut kinds = allowed_kinds;
    kinds.sort_unstable();
    kinds.dedup();

    let signing_approved = methods.iter().any(|method| method == "sign_event");
    if !signing_approved && !kinds.is_empty() {
        return Err("event kinds require sign_event permission");
    }

    Ok(ExactSlotPolicy {
        allowed_methods: methods,
        allowed_kinds: kinds,
        auto_approve,
        signing_approved,
    })
}

/// Evaluate the policy-controlled part of a slot request. Protocol-wide
/// invariants such as ping/get_public_key are handled by the caller first; this
/// helper is deliberately pure so the firmware's exact deny boundary runs in
/// host CI as well as on the ESP.
pub fn evaluate_slot_policy(
    slot: &ConnectSlot,
    method: &str,
    event_kind: Option<u64>,
) -> ApprovalTier {
    if !slot.allowed_methods.iter().any(|allowed| allowed == method) {
        return if strict_slot_denies_method(slot, method) {
            ApprovalTier::Denied
        } else {
            ApprovalTier::ButtonRequired
        };
    }

    if method == "sign_event" {
        if !slot.signing_approved {
            return if slot.strict_permissions {
                ApprovalTier::Denied
            } else {
                ApprovalTier::ButtonRequired
            };
        }
        if let Some(kind) = event_kind {
            if !slot.allowed_kinds.is_empty() && !slot.allowed_kinds.contains(&kind) {
                return if slot.strict_permissions {
                    ApprovalTier::Denied
                } else {
                    ApprovalTier::ButtonRequired
                };
            }
        }
    }

    if slot.auto_approve {
        ApprovalTier::AutoApprove
    } else {
        ApprovalTier::ButtonRequired
    }
}

/// Exact v2 slots impose a hard method ceiling before legacy Heartwood method
/// invariants (button, OLED notify, or always-auto) are considered.
pub fn strict_slot_denies_method(slot: &ConnectSlot, method: &str) -> bool {
    slot.strict_permissions
        && !slot
            .allowed_methods
            .iter()
            .any(|allowed| allowed == method)
}

/// Grant sign_event after an explicit button/operator approval without
/// broadening any previously configured encryption or event-kind ceiling.
pub fn grant_slot_signing(slot: &mut ConnectSlot) {
    slot.signing_approved = true;
    if !slot
        .allowed_methods
        .iter()
        .any(|method| method == "sign_event")
    {
        slot.allowed_methods.insert(0, "sign_event".to_string());
    }
}

/// Approval decision for a specific request.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ApprovalTier {
    /// Proceed immediately without user interaction.
    AutoApprove,
    /// Show briefly on OLED (1s) but don't wait for button.
    OledNotify,
    /// Full OLED display with countdown bar, wait for button approval.
    ButtonRequired,
    /// The request is outside the operator-approved policy ceiling.
    Denied,
}

// ---------------------------------------------------------------------------
// Pure policy helpers (testable on host, used by firmware PolicyEngine)
// ---------------------------------------------------------------------------

/// Create a connect-time TOFU policy (no signing -- only granted on valid secret).
pub fn make_connect_policy(client_pubkey: &str) -> ClientPolicy {
    ClientPolicy {
        client_pubkey: client_pubkey.to_string(),
        label: String::new(),
        allowed_methods: CONNECT_SAFE_METHODS.iter().map(|s| s.to_string()).collect(),
        allowed_kinds: vec![],
        auto_approve: true,
    }
}

/// Create a full TOFU policy for a client after first physical button approval.
/// Includes sign_event -- only call this after the user has pressed the button.
pub fn make_tofu_policy(client_pubkey: &str) -> ClientPolicy {
    ClientPolicy {
        client_pubkey: client_pubkey.to_string(),
        label: String::new(),
        allowed_methods: TOFU_SAFE_METHODS.iter().map(|s| s.to_string()).collect(),
        allowed_kinds: vec![],
        auto_approve: true,
    }
}

/// Find a policy by client pubkey.
pub fn find_policy<'a>(
    policies: &'a [ClientPolicy],
    client_pubkey: &str,
) -> Option<&'a ClientPolicy> {
    policies.iter().find(|p| p.client_pubkey == client_pubkey)
}

/// Remove a client policy by pubkey. Returns true if found and removed.
pub fn revoke_policy(policies: &mut Vec<ClientPolicy>, client_pubkey: &str) -> bool {
    let before = policies.len();
    policies.retain(|p| p.client_pubkey != client_pubkey);
    policies.len() < before
}

/// Upsert a client policy. Replaces if client_pubkey matches, otherwise adds.
pub fn upsert_policy(policies: &mut Vec<ClientPolicy>, policy: ClientPolicy) {
    if let Some(existing) = policies
        .iter_mut()
        .find(|p| p.client_pubkey == policy.client_pubkey)
    {
        *existing = policy;
    } else {
        policies.push(policy);
    }
}

// ---------------------------------------------------------------------------
// ConnectSlot helpers (testable on host, used by firmware PolicyEngine)
// ---------------------------------------------------------------------------

/// True if `pubkey` is authorised for this slot -- either the current binding
/// or any pubkey that has previously paired with the slot secret.
pub fn slot_authorizes(slot: &ConnectSlot, pubkey: &str) -> bool {
    slot.current_pubkey.as_deref() == Some(pubkey)
        || slot.authorized_pubkeys.iter().any(|p| p == pubkey)
}

/// Authorise `pubkey` on a slot: make it the current binding and remember it in
/// `authorized_pubkeys`. The outgoing `current_pubkey` is preserved in the set,
/// so an earlier device stays auto-approved instead of being evicted. The set
/// is de-duplicated and FIFO-capped at [`MAX_AUTHORIZED_PUBKEYS`].
pub fn authorize_pubkey_on_slot(slot: &mut ConnectSlot, pubkey: &str) {
    if let Some(prev) = slot.current_pubkey.take() {
        if prev != pubkey {
            push_authorized(slot, prev);
        }
    }
    push_authorized(slot, pubkey.to_string());
    slot.current_pubkey = Some(pubkey.to_string());
}

/// Move `pubkey` onto exactly one slot within a master, then authorise it there.
///
/// A client key must never inherit whichever policy happens to appear first in
/// the slot vector. Before binding the target, remove that key from every other
/// slot's current and retained-authority fields. Other clients sharing those
/// slots are preserved. Returns false without mutation when `slot_index` does
/// not exist.
pub fn authorize_pubkey_on_unique_slot(
    slots: &mut [ConnectSlot],
    slot_index: u8,
    pubkey: &str,
) -> bool {
    let Some(target_pos) = slots.iter().position(|slot| slot.slot_index == slot_index) else {
        return false;
    };

    for (position, slot) in slots.iter_mut().enumerate() {
        if position == target_pos {
            continue;
        }
        if slot.current_pubkey.as_deref() == Some(pubkey) {
            slot.current_pubkey = None;
        }
        slot.authorized_pubkeys.retain(|candidate| candidate != pubkey);
    }

    authorize_pubkey_on_slot(&mut slots[target_pos], pubkey);
    true
}

/// Remove every client pubkey that is authorised by more than one slot.
///
/// This is the fail-closed boot migration for state written before unique slot
/// ownership was enforced. Picking the first or last slot could silently retain
/// the broader policy; removing an ambiguous key from all slots forces the app
/// to prove possession of exactly one slot secret on its next connect. Returns
/// true when any authority field changed.
pub fn remove_ambiguous_pubkeys(slots: &mut [ConnectSlot]) -> bool {
    let mut owners: Vec<(String, usize)> = Vec::new();
    let mut ambiguous: Vec<String> = Vec::new();

    for (position, slot) in slots.iter().enumerate() {
        for pubkey in slot
            .current_pubkey
            .iter()
            .chain(slot.authorized_pubkeys.iter())
        {
            if ambiguous.iter().any(|candidate| candidate == pubkey) {
                continue;
            }
            match owners.iter().find(|(candidate, _)| candidate == pubkey) {
                Some((_, owner)) if *owner != position => ambiguous.push(pubkey.clone()),
                Some(_) => {}
                None => owners.push((pubkey.clone(), position)),
            }
        }
    }

    if ambiguous.is_empty() {
        return false;
    }

    let mut changed = false;
    for slot in slots.iter_mut() {
        if slot
            .current_pubkey
            .as_ref()
            .map(|pubkey| ambiguous.iter().any(|candidate| candidate == pubkey))
            .unwrap_or(false)
        {
            slot.current_pubkey = None;
            changed = true;
        }
        let before = slot.authorized_pubkeys.len();
        slot.authorized_pubkeys
            .retain(|pubkey| !ambiguous.iter().any(|candidate| candidate == pubkey));
        changed |= slot.authorized_pubkeys.len() != before;
    }
    changed
}

/// Add a pubkey to a slot's authorised set (de-duplicated, FIFO-capped).
fn push_authorized(slot: &mut ConnectSlot, pubkey: String) {
    if slot.authorized_pubkeys.iter().any(|p| *p == pubkey) {
        return;
    }
    while slot.authorized_pubkeys.len() >= MAX_AUTHORIZED_PUBKEYS {
        slot.authorized_pubkeys.remove(0);
    }
    slot.authorized_pubkeys.push(pubkey);
}

/// Find a slot that authorises this client pubkey (current binding or set).
pub fn find_slot_by_pubkey<'a>(slots: &'a [ConnectSlot], pubkey: &str) -> Option<&'a ConnectSlot> {
    slots.iter().find(|s| slot_authorizes(s, pubkey))
}

/// Find a mutable slot that authorises this client pubkey (current binding or set).
pub fn find_slot_by_pubkey_mut<'a>(
    slots: &'a mut [ConnectSlot],
    pubkey: &str,
) -> Option<&'a mut ConnectSlot> {
    slots.iter_mut().find(|s| slot_authorizes(s, pubkey))
}

/// Find a slot by its secret using constant-time comparison.
/// Always iterates all slots to prevent timing-based slot identification.
/// Returns the first matching slot (lowest index).
pub fn find_slot_by_secret<'a>(slots: &'a [ConnectSlot], secret: &str) -> Option<&'a ConnectSlot> {
    let mut matched: Option<usize> = None;
    for (i, slot) in slots.iter().enumerate() {
        if constant_time_eq_str(&slot.secret, secret) && matched.is_none() {
            matched = Some(i);
        }
    }
    matched.map(|i| &slots[i])
}

/// Find a mutable slot by its secret using constant-time comparison.
/// Always iterates all slots to prevent timing-based slot identification.
/// Returns the first matching slot (lowest index).
pub fn find_slot_by_secret_mut<'a>(
    slots: &'a mut [ConnectSlot],
    secret: &str,
) -> Option<&'a mut ConnectSlot> {
    let mut matched: Option<usize> = None;
    for (i, slot) in slots.iter().enumerate() {
        if constant_time_eq_str(&slot.secret, secret) && matched.is_none() {
            matched = Some(i);
        }
    }
    matched.map(move |i| &mut slots[i])
}

/// Find the next available slot index (0-15). Returns None if all 16 are occupied.
pub fn next_slot_index(slots: &[ConnectSlot]) -> Option<u8> {
    for i in 0..MAX_CONNECT_SLOTS {
        if !slots.iter().any(|s| s.slot_index == i) {
            return Some(i);
        }
    }
    None
}

/// Create a redacted copy of a slot (secret replaced with empty string).
pub fn redact_slot(slot: &ConnectSlot) -> ConnectSlot {
    ConnectSlot {
        secret: String::new(),
        ..slot.clone()
    }
}

/// Constant-time string equality (prevents timing attacks on secret comparison).
fn constant_time_eq_str(a: &str, b: &str) -> bool {
    let a = a.as_bytes();
    let b = b.as_bytes();
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_pubkey(c: char) -> String {
        c.to_string().repeat(64)
    }

    fn sample_policy(c: char) -> ClientPolicy {
        ClientPolicy {
            client_pubkey: sample_pubkey(c),
            label: format!("Client {c}"),
            allowed_methods: vec!["sign_event".into()],
            allowed_kinds: vec![1, 7],
            auto_approve: true,
        }
    }

    // --- Serde roundtrip ---

    #[test]
    fn serde_roundtrip() {
        let policy = sample_policy('a');
        let json = serde_json::to_string(&policy).unwrap();
        let decoded: ClientPolicy = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.client_pubkey, policy.client_pubkey);
        assert_eq!(decoded.label, "Client a");
        assert_eq!(decoded.allowed_kinds, vec![1, 7]);
        assert!(decoded.auto_approve);
    }

    #[test]
    fn serde_defaults() {
        // Minimal JSON with only the required field.
        let json = r#"{"client_pubkey":"aa"}"#;
        let policy: ClientPolicy = serde_json::from_str(json).unwrap();
        assert_eq!(policy.client_pubkey, "aa");
        assert_eq!(policy.label, "");
        assert!(policy.allowed_methods.is_empty());
        assert!(policy.allowed_kinds.is_empty());
        assert!(!policy.auto_approve);
    }

    #[test]
    fn serde_vec_roundtrip() {
        let policies = vec![sample_policy('a'), sample_policy('b')];
        let json = serde_json::to_string(&policies).unwrap();
        let decoded: Vec<ClientPolicy> = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.len(), 2);
        assert_eq!(decoded[0].label, "Client a");
        assert_eq!(decoded[1].label, "Client b");
    }

    // --- TOFU defaults ---

    #[test]
    fn tofu_policy_has_correct_defaults() {
        let policy = make_tofu_policy(&sample_pubkey('x'));
        assert!(policy.auto_approve);
        assert!(policy.label.is_empty());
        assert!(policy.allowed_kinds.is_empty());
        assert_eq!(policy.allowed_methods.len(), TOFU_SAFE_METHODS.len());
        for method in TOFU_SAFE_METHODS {
            assert!(policy.allowed_methods.contains(&method.to_string()));
        }
    }

    #[test]
    fn tofu_safe_methods_includes_essentials() {
        assert!(TOFU_SAFE_METHODS.contains(&"sign_event"));
        assert!(TOFU_SAFE_METHODS.contains(&"nip44_encrypt"));
        assert!(TOFU_SAFE_METHODS.contains(&"nip44_decrypt"));
        assert!(TOFU_SAFE_METHODS.contains(&"get_public_key"));
    }

    // --- Connect-safe methods ---

    #[test]
    fn connect_safe_methods_excludes_signing() {
        assert!(!CONNECT_SAFE_METHODS.contains(&"sign_event"));
    }

    #[test]
    fn connect_safe_methods_includes_crypto() {
        assert!(CONNECT_SAFE_METHODS.contains(&"nip44_encrypt"));
        assert!(CONNECT_SAFE_METHODS.contains(&"nip44_decrypt"));
        assert!(CONNECT_SAFE_METHODS.contains(&"nip04_encrypt"));
        assert!(CONNECT_SAFE_METHODS.contains(&"nip04_decrypt"));
        assert!(CONNECT_SAFE_METHODS.contains(&"get_public_key"));
    }

    #[test]
    fn connect_safe_is_subset_of_tofu_safe() {
        for method in CONNECT_SAFE_METHODS {
            assert!(
                TOFU_SAFE_METHODS.contains(method),
                "{} is in CONNECT_SAFE but not TOFU_SAFE",
                method
            );
        }
    }

    #[test]
    fn connect_policy_has_correct_defaults() {
        let policy = make_connect_policy(&sample_pubkey('x'));
        assert!(policy.auto_approve);
        assert!(policy.label.is_empty());
        assert!(policy.allowed_kinds.is_empty());
        assert_eq!(policy.allowed_methods.len(), CONNECT_SAFE_METHODS.len());
        assert!(!policy.allowed_methods.contains(&"sign_event".to_string()));
        for method in CONNECT_SAFE_METHODS {
            assert!(policy.allowed_methods.contains(&method.to_string()));
        }
    }

    // --- Exact remotely-managed slot policies ---

    #[test]
    fn exact_policy_is_canonical_and_derives_signing_gate() {
        let policy = validate_exact_slot_policy(
            vec![
                "get_public_key".into(),
                "sign_event".into(),
                "sign_event".into(),
            ],
            vec![1059, 13, 13],
            true,
        )
        .unwrap();

        assert_eq!(policy.allowed_methods, vec!["get_public_key", "sign_event"]);
        assert_eq!(policy.allowed_kinds, vec![13, 1059]);
        assert!(policy.auto_approve);
        assert!(policy.signing_approved);
    }

    #[test]
    fn exact_policy_can_grant_crypto_without_signing() {
        let policy = validate_exact_slot_policy(
            vec!["get_public_key".into(), "nip44_decrypt".into()],
            vec![],
            true,
        )
        .unwrap();

        assert!(!policy.signing_approved);
        assert!(!policy.allowed_methods.contains(&"sign_event".to_string()));
    }

    #[test]
    fn exact_policy_rejects_unknown_methods_and_orphan_kinds() {
        assert_eq!(
            validate_exact_slot_policy(vec!["delete_everything".into()], vec![], true),
            Err("policy contains an unsupported method"),
        );
        assert_eq!(
            validate_exact_slot_policy(vec!["get_public_key".into()], vec![1], true),
            Err("event kinds require sign_event permission"),
        );
    }

    #[test]
    fn exact_policy_bounds_kind_count() {
        let kinds = (0..=MAX_ALLOWED_KINDS as u64).collect();
        assert_eq!(
            validate_exact_slot_policy(vec!["sign_event".into()], kinds, true),
            Err("policy contains too many event kinds"),
        );
    }

    // --- Find ---

    #[test]
    fn find_existing_policy() {
        let policies = vec![sample_policy('a'), sample_policy('b')];
        let found = find_policy(&policies, &sample_pubkey('b'));
        assert!(found.is_some());
        assert_eq!(found.unwrap().label, "Client b");
    }

    #[test]
    fn find_missing_policy() {
        let policies = vec![sample_policy('a')];
        assert!(find_policy(&policies, &sample_pubkey('z')).is_none());
    }

    #[test]
    fn find_in_empty_list() {
        let policies: Vec<ClientPolicy> = vec![];
        assert!(find_policy(&policies, &sample_pubkey('a')).is_none());
    }

    // --- Revoke ---

    #[test]
    fn revoke_existing_policy() {
        let mut policies = vec![sample_policy('a'), sample_policy('b'), sample_policy('c')];
        assert!(revoke_policy(&mut policies, &sample_pubkey('b')));
        assert_eq!(policies.len(), 2);
        assert!(find_policy(&policies, &sample_pubkey('b')).is_none());
        // Others untouched.
        assert!(find_policy(&policies, &sample_pubkey('a')).is_some());
        assert!(find_policy(&policies, &sample_pubkey('c')).is_some());
    }

    #[test]
    fn revoke_missing_policy() {
        let mut policies = vec![sample_policy('a')];
        assert!(!revoke_policy(&mut policies, &sample_pubkey('z')));
        assert_eq!(policies.len(), 1);
    }

    #[test]
    fn revoke_from_empty_list() {
        let mut policies: Vec<ClientPolicy> = vec![];
        assert!(!revoke_policy(&mut policies, &sample_pubkey('a')));
    }

    // --- Upsert ---

    #[test]
    fn upsert_adds_new_policy() {
        let mut policies = vec![sample_policy('a')];
        upsert_policy(&mut policies, sample_policy('b'));
        assert_eq!(policies.len(), 2);
        assert_eq!(
            find_policy(&policies, &sample_pubkey('b')).unwrap().label,
            "Client b"
        );
    }

    #[test]
    fn upsert_replaces_existing_policy() {
        let mut policies = vec![sample_policy('a')];
        let mut updated = sample_policy('a');
        updated.label = "Updated".into();
        updated.auto_approve = false;
        upsert_policy(&mut policies, updated);
        assert_eq!(policies.len(), 1);
        let found = find_policy(&policies, &sample_pubkey('a')).unwrap();
        assert_eq!(found.label, "Updated");
        assert!(!found.auto_approve);
    }

    #[test]
    fn upsert_into_empty_list() {
        let mut policies: Vec<ClientPolicy> = vec![];
        upsert_policy(&mut policies, sample_policy('a'));
        assert_eq!(policies.len(), 1);
    }

    // --- Approval tier ---

    #[test]
    fn approval_tier_values_are_distinct() {
        assert_ne!(ApprovalTier::AutoApprove, ApprovalTier::ButtonRequired);
        assert_ne!(ApprovalTier::AutoApprove, ApprovalTier::OledNotify);
        assert_ne!(ApprovalTier::AutoApprove, ApprovalTier::Denied);
        assert_ne!(ApprovalTier::OledNotify, ApprovalTier::ButtonRequired);
    }

    // --- ConnectSlot ---

    fn sample_slot(index: u8, label: &str) -> ConnectSlot {
        ConnectSlot {
            slot_index: index,
            label: label.to_string(),
            secret: "ab".repeat(32),
            current_pubkey: None,
            allowed_methods: CONNECT_SAFE_METHODS.iter().map(|s| s.to_string()).collect(),
            allowed_kinds: vec![],
            auto_approve: true,
            signing_approved: false,
            strict_permissions: false,
            authorized_pubkeys: vec![],
        }
    }

    #[test]
    fn strict_slot_denies_methods_and_kinds_outside_the_ceiling() {
        let mut slot = sample_slot(0, "strict");
        slot.strict_permissions = true;
        slot.allowed_methods = vec!["get_public_key".into(), "sign_event".into()];
        slot.allowed_kinds = vec![1, 7];
        slot.signing_approved = true;

        assert_eq!(
            evaluate_slot_policy(&slot, "sign_event", Some(1)),
            ApprovalTier::AutoApprove,
        );
        assert_eq!(
            evaluate_slot_policy(&slot, "sign_event", Some(0)),
            ApprovalTier::Denied,
        );
        assert_eq!(
            evaluate_slot_policy(&slot, "nip44_decrypt", None),
            ApprovalTier::Denied,
        );
    }

    #[test]
    fn strict_slot_requires_explicit_signing_approval() {
        let mut slot = sample_slot(0, "strict");
        slot.strict_permissions = true;
        slot.allowed_methods = vec!["sign_event".into()];
        slot.signing_approved = false;
        assert_eq!(
            evaluate_slot_policy(&slot, "sign_event", Some(1)),
            ApprovalTier::Denied,
        );
    }

    #[test]
    fn strict_slot_denies_unlisted_heartwood_extensions() {
        let mut slot = sample_slot(0, "strict-posting");
        slot.strict_permissions = true;
        slot.allowed_methods = vec!["get_public_key".into(), "sign_event".into()];
        slot.signing_approved = true;

        for extension in [
            "heartwood_derive",
            "heartwood_switch",
            "heartwood_list_identities",
            "heartwood_verify_proof",
        ] {
            assert!(strict_slot_denies_method(&slot, extension));
            assert_eq!(
                evaluate_slot_policy(&slot, extension, None),
                ApprovalTier::Denied,
                "{extension} escaped the strict method ceiling",
            );
        }

        slot.strict_permissions = false;
        assert!(!strict_slot_denies_method(&slot, "heartwood_derive"));
    }

    #[test]
    fn legacy_slot_retains_button_fallback_but_empty_methods_never_auto_approve() {
        let mut slot = sample_slot(0, "legacy");
        slot.allowed_methods.clear();
        assert_eq!(
            evaluate_slot_policy(&slot, "sign_event", Some(1)),
            ApprovalTier::ButtonRequired,
        );
    }

    #[test]
    fn signing_upgrade_preserves_existing_method_and_kind_ceiling() {
        let mut slot = sample_slot(0, "posting");
        slot.allowed_methods = vec!["get_public_key".into()];
        slot.allowed_kinds = vec![1, 7];

        grant_slot_signing(&mut slot);
        assert!(slot.signing_approved);
        assert_eq!(slot.allowed_methods, vec!["sign_event", "get_public_key"]);
        assert_eq!(slot.allowed_kinds, vec![1, 7]);

        grant_slot_signing(&mut slot);
        assert_eq!(slot.allowed_methods, vec!["sign_event", "get_public_key"]);
    }

    #[test]
    fn connect_slot_serde_roundtrip() {
        let slot = sample_slot(0, "nostrudel desktop");
        let json = serde_json::to_string(&slot).unwrap();
        let decoded: ConnectSlot = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.slot_index, 0);
        assert_eq!(decoded.label, "nostrudel desktop");
        assert_eq!(decoded.secret, "ab".repeat(32));
        assert!(decoded.current_pubkey.is_none());
        assert!(!decoded.signing_approved);
    }

    #[test]
    fn connect_slot_serde_with_pubkey() {
        let mut slot = sample_slot(3, "Bark laptop");
        slot.current_pubkey = Some(sample_pubkey('c'));
        slot.signing_approved = true;
        let json = serde_json::to_string(&slot).unwrap();
        let decoded: ConnectSlot = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.current_pubkey, Some(sample_pubkey('c')));
        assert!(decoded.signing_approved);
    }

    #[test]
    fn connect_slot_vec_serde_roundtrip() {
        let slots = vec![
            sample_slot(0, "nostrudel desktop"),
            sample_slot(1, "Bark laptop"),
        ];
        let json = serde_json::to_string(&slots).unwrap();
        let decoded: Vec<ConnectSlot> = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.len(), 2);
        assert_eq!(decoded[0].label, "nostrudel desktop");
        assert_eq!(decoded[1].slot_index, 1);
    }

    #[test]
    fn connect_slot_defaults() {
        let json = r#"{"slot_index":0,"label":"test","secret":"aa"}"#;
        let slot: ConnectSlot = serde_json::from_str(json).unwrap();
        assert!(slot.current_pubkey.is_none());
        assert!(slot.allowed_methods.is_empty());
        assert!(slot.allowed_kinds.is_empty());
        assert!(!slot.auto_approve);
        assert!(!slot.signing_approved);
        assert!(!slot.strict_permissions);
        // Old NVS blobs (no field) deserialise to an empty authorised set.
        assert!(slot.authorized_pubkeys.is_empty());
    }

    #[test]
    fn authorize_preserves_previous_client() {
        let mut slot = sample_slot(0, "Signet");
        authorize_pubkey_on_slot(&mut slot, &sample_pubkey('a'));
        authorize_pubkey_on_slot(&mut slot, &sample_pubkey('b'));
        // Most recent is current; the earlier client is retained, not evicted.
        assert_eq!(slot.current_pubkey, Some(sample_pubkey('b')));
        assert!(slot_authorizes(&slot, &sample_pubkey('a')));
        assert!(slot_authorizes(&slot, &sample_pubkey('b')));
        assert_eq!(slot.authorized_pubkeys.len(), 2);
    }

    #[test]
    fn authorize_is_idempotent() {
        let mut slot = sample_slot(0, "Signet");
        authorize_pubkey_on_slot(&mut slot, &sample_pubkey('a'));
        authorize_pubkey_on_slot(&mut slot, &sample_pubkey('a'));
        assert_eq!(slot.authorized_pubkeys, vec![sample_pubkey('a')]);
        assert_eq!(slot.current_pubkey, Some(sample_pubkey('a')));
    }

    #[test]
    fn reauthorizing_earlier_client_keeps_both() {
        let mut slot = sample_slot(0, "Signet");
        authorize_pubkey_on_slot(&mut slot, &sample_pubkey('a'));
        authorize_pubkey_on_slot(&mut slot, &sample_pubkey('b'));
        authorize_pubkey_on_slot(&mut slot, &sample_pubkey('a')); // 'a' reconnects
        assert_eq!(slot.current_pubkey, Some(sample_pubkey('a')));
        assert_eq!(slot.authorized_pubkeys.len(), 2);
        assert!(slot_authorizes(&slot, &sample_pubkey('a')));
        assert!(slot_authorizes(&slot, &sample_pubkey('b')));
    }

    #[test]
    fn find_slot_by_pubkey_matches_set_member() {
        // current_pubkey is 'b', but 'a' is still in the authorised set.
        let mut slot = sample_slot(0, "Signet");
        authorize_pubkey_on_slot(&mut slot, &sample_pubkey('a'));
        authorize_pubkey_on_slot(&mut slot, &sample_pubkey('b'));
        let slots = vec![slot, sample_slot(1, "other")];
        assert!(find_slot_by_pubkey(&slots, &sample_pubkey('a')).is_some());
        assert!(find_slot_by_pubkey(&slots, &sample_pubkey('b')).is_some());
    }

    #[test]
    fn unique_assignment_moves_client_out_of_every_other_slot() {
        let client = sample_pubkey('a');
        let retained = sample_pubkey('b');
        let mut first = sample_slot(0, "older broad policy");
        authorize_pubkey_on_slot(&mut first, &retained);
        authorize_pubkey_on_slot(&mut first, &client);
        let mut target = sample_slot(1, "new strict policy");
        let mut third = sample_slot(2, "stale duplicate");
        third.current_pubkey = Some(client.clone());
        let mut slots = vec![first, target.clone(), third];

        assert!(authorize_pubkey_on_unique_slot(&mut slots, 1, &client));

        assert!(!slot_authorizes(&slots[0], &client));
        assert!(slot_authorizes(&slots[0], &retained));
        assert!(slot_authorizes(&slots[1], &client));
        assert_eq!(slots[1].current_pubkey.as_deref(), Some(client.as_str()));
        assert!(!slot_authorizes(&slots[2], &client));
        assert!(slots[2].current_pubkey.is_none());

        // Keep the fixture honest: assignment changed only authority fields on
        // the target; its policy/secret identity remains the requested slot.
        target.current_pubkey = Some(client.clone());
        target.authorized_pubkeys.push(client);
        assert_eq!(slots[1].slot_index, target.slot_index);
        assert_eq!(slots[1].secret, target.secret);
        assert_eq!(slots[1].allowed_methods, target.allowed_methods);
    }

    #[test]
    fn unique_assignment_missing_target_is_an_atomic_noop() {
        let client = sample_pubkey('a');
        let mut slot = sample_slot(0, "existing");
        authorize_pubkey_on_slot(&mut slot, &client);
        let before = serde_json::to_string(&slot).unwrap();
        let mut slots = vec![slot];

        assert!(!authorize_pubkey_on_unique_slot(&mut slots, 9, &client));
        assert_eq!(serde_json::to_string(&slots[0]).unwrap(), before);
    }

    #[test]
    fn boot_migration_removes_ambiguous_client_from_broad_and_strict_slots() {
        let duplicate = sample_pubkey('a');
        let unique = sample_pubkey('b');
        let mut broad = sample_slot(0, "old broad");
        broad.allowed_methods.push("sign_event".into());
        broad.signing_approved = true;
        authorize_pubkey_on_slot(&mut broad, &unique);
        authorize_pubkey_on_slot(&mut broad, &duplicate);

        let mut strict = sample_slot(1, "new strict");
        strict.strict_permissions = true;
        strict.allowed_methods = vec!["get_public_key".into()];
        strict.current_pubkey = Some(duplicate.clone());
        strict.authorized_pubkeys = vec![duplicate.clone()];
        let mut slots = vec![broad, strict];

        assert!(remove_ambiguous_pubkeys(&mut slots));
        assert!(!slot_authorizes(&slots[0], &duplicate));
        assert!(!slot_authorizes(&slots[1], &duplicate));
        assert!(slot_authorizes(&slots[0], &unique));
        assert!(find_slot_by_pubkey(&slots, &duplicate).is_none());
        assert!(!remove_ambiguous_pubkeys(&mut slots));
    }

    #[test]
    fn authorize_caps_at_max_fifo() {
        let mut slot = sample_slot(0, "Signet");
        // Authorise MAX + 2 distinct clients.
        for i in 0..(MAX_AUTHORIZED_PUBKEYS + 2) {
            authorize_pubkey_on_slot(&mut slot, &format!("{i:0>64x}"));
        }
        assert_eq!(slot.authorized_pubkeys.len(), MAX_AUTHORIZED_PUBKEYS);
        // The two oldest were dropped (FIFO).
        assert!(!slot_authorizes(&slot, &format!("{:0>64x}", 0)));
        assert!(!slot_authorizes(&slot, &format!("{:0>64x}", 1)));
        // The newest is still current and authorised.
        let last = format!("{:0>64x}", MAX_AUTHORIZED_PUBKEYS + 1);
        assert_eq!(slot.current_pubkey, Some(last.clone()));
        assert!(slot_authorizes(&slot, &last));
    }

    #[test]
    fn find_slot_by_pubkey_found() {
        let mut slot = sample_slot(0, "test");
        slot.current_pubkey = Some(sample_pubkey('a'));
        let slots = vec![slot, sample_slot(1, "other")];
        let found = find_slot_by_pubkey(&slots, &sample_pubkey('a'));
        assert!(found.is_some());
        assert_eq!(found.unwrap().label, "test");
    }

    #[test]
    fn find_slot_by_pubkey_not_found() {
        let slots = vec![sample_slot(0, "test")];
        assert!(find_slot_by_pubkey(&slots, &sample_pubkey('z')).is_none());
    }

    #[test]
    fn find_slot_by_pubkey_empty() {
        let slots: Vec<ConnectSlot> = vec![];
        assert!(find_slot_by_pubkey(&slots, &sample_pubkey('a')).is_none());
    }

    #[test]
    fn find_slot_by_secret_found() {
        let slots = vec![sample_slot(0, "first"), sample_slot(1, "second")];
        // sample_slot uses "ab".repeat(32) for secret
        let found = find_slot_by_secret(&slots, &"ab".repeat(32));
        assert!(found.is_some());
        // Both have same secret in this test -- first match wins
        assert_eq!(found.unwrap().slot_index, 0);
    }

    #[test]
    fn find_slot_by_secret_not_found() {
        let slots = vec![sample_slot(0, "test")];
        assert!(find_slot_by_secret(&slots, &"ff".repeat(32)).is_none());
    }

    #[test]
    fn next_slot_index_empty() {
        let slots: Vec<ConnectSlot> = vec![];
        assert_eq!(next_slot_index(&slots), Some(0));
    }

    #[test]
    fn next_slot_index_gaps() {
        let slots = vec![sample_slot(0, "a"), sample_slot(2, "c")];
        assert_eq!(next_slot_index(&slots), Some(1));
    }

    #[test]
    fn next_slot_index_full() {
        let slots: Vec<ConnectSlot> = (0..16).map(|i| sample_slot(i, "x")).collect();
        assert_eq!(next_slot_index(&slots), None);
    }

    #[test]
    fn redact_slot_hides_secret() {
        let slot = sample_slot(0, "test");
        let redacted = redact_slot(&slot);
        assert!(redacted.secret.is_empty());
        assert_eq!(redacted.label, "test");
        assert_eq!(redacted.slot_index, 0);
    }
}
