// common/src/policy.rs
//
// Client approval policy types shared between firmware and bridge.

use serde::{Deserialize, Serialize};

/// Maximum connection slots per master.
pub const MAX_CONNECT_SLOTS: u8 = 16;

/// A named connection slot for a specific master.
///
/// Each slot has its own bunker URI secret. The slot -- not the ephemeral
/// client pubkey -- is the stable identity. When a client reconnects with
/// a new ephemeral key, the slot's pubkey is swapped and permissions carry over.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ConnectSlot {
    /// Slot index (0-15).
    pub slot_index: u8,
    /// Human-readable label (e.g. "nostrudel desktop").
    pub label: String,
    /// Hex-encoded 32-byte secret (64 chars). Generated by hardware RNG.
    pub secret: String,
    /// Hex-encoded current client pubkey, set on first connect.
    #[serde(default)]
    pub current_pubkey: Option<String>,
    /// Which NIP-46 methods are auto-approved for this slot.
    #[serde(default)]
    pub allowed_methods: Vec<String>,
    /// Which event kinds are auto-approved for sign_event.
    #[serde(default)]
    pub allowed_kinds: Vec<u64>,
    /// Whether to auto-approve matching requests (true) or just OLED-notify (false).
    #[serde(default)]
    pub auto_approve: bool,
    /// True once the user has physically approved a sign_event via button press.
    #[serde(default)]
    pub signing_approved: bool,
}

/// A client's approval policy for a specific master.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ClientPolicy {
    /// Hex-encoded client public key (64 chars).
    pub client_pubkey: String,
    /// Human-readable label (e.g. "Bark browser").
    #[serde(default)]
    pub label: String,
    /// Which NIP-46 methods are auto-approved.
    #[serde(default)]
    pub allowed_methods: Vec<String>,
    /// Which event kinds are auto-approved for sign_event.
    /// Empty = all kinds allowed.
    #[serde(default)]
    pub allowed_kinds: Vec<u64>,
    /// Whether to auto-approve matching requests (true) or just OLED-notify (false).
    #[serde(default)]
    pub auto_approve: bool,
}

/// Methods auto-approved on connect when the client provides a valid secret.
/// These are non-signing operations -- safe to grant without physical approval.
pub const CONNECT_SAFE_METHODS: &[&str] = &[
    "nip44_encrypt",
    "nip44_decrypt",
    "nip04_encrypt",
    "nip04_decrypt",
    "get_public_key",
];

/// Methods auto-approved after first physical button approval.
/// Includes signing -- only granted after the user explicitly approves once.
pub const TOFU_SAFE_METHODS: &[&str] = &[
    "sign_event",
    "nip44_encrypt",
    "nip44_decrypt",
    "nip04_encrypt",
    "nip04_decrypt",
    "get_public_key",
];

/// Approval decision for a specific request.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ApprovalTier {
    /// Proceed immediately without user interaction.
    AutoApprove,
    /// Show briefly on OLED (1s) but don't wait for button.
    OledNotify,
    /// Full OLED display with countdown bar, wait for button approval.
    ButtonRequired,
}

// ---------------------------------------------------------------------------
// Pure policy helpers (testable on host, used by firmware PolicyEngine)
// ---------------------------------------------------------------------------

/// Create a connect-time TOFU policy (no signing -- only granted on valid secret).
pub fn make_connect_policy(client_pubkey: &str) -> ClientPolicy {
    ClientPolicy {
        client_pubkey: client_pubkey.to_string(),
        label: String::new(),
        allowed_methods: CONNECT_SAFE_METHODS.iter().map(|s| s.to_string()).collect(),
        allowed_kinds: vec![],
        auto_approve: true,
    }
}

/// Create a full TOFU policy for a client after first physical button approval.
/// Includes sign_event -- only call this after the user has pressed the button.
pub fn make_tofu_policy(client_pubkey: &str) -> ClientPolicy {
    ClientPolicy {
        client_pubkey: client_pubkey.to_string(),
        label: String::new(),
        allowed_methods: TOFU_SAFE_METHODS.iter().map(|s| s.to_string()).collect(),
        allowed_kinds: vec![],
        auto_approve: true,
    }
}

/// Find a policy by client pubkey.
pub fn find_policy<'a>(policies: &'a [ClientPolicy], client_pubkey: &str) -> Option<&'a ClientPolicy> {
    policies.iter().find(|p| p.client_pubkey == client_pubkey)
}

/// Remove a client policy by pubkey. Returns true if found and removed.
pub fn revoke_policy(policies: &mut Vec<ClientPolicy>, client_pubkey: &str) -> bool {
    let before = policies.len();
    policies.retain(|p| p.client_pubkey != client_pubkey);
    policies.len() < before
}

/// Upsert a client policy. Replaces if client_pubkey matches, otherwise adds.
pub fn upsert_policy(policies: &mut Vec<ClientPolicy>, policy: ClientPolicy) {
    if let Some(existing) = policies.iter_mut().find(|p| p.client_pubkey == policy.client_pubkey) {
        *existing = policy;
    } else {
        policies.push(policy);
    }
}

// ---------------------------------------------------------------------------
// ConnectSlot helpers (testable on host, used by firmware PolicyEngine)
// ---------------------------------------------------------------------------

/// Find a slot by its current client pubkey.
pub fn find_slot_by_pubkey<'a>(slots: &'a [ConnectSlot], pubkey: &str) -> Option<&'a ConnectSlot> {
    slots.iter().find(|s| s.current_pubkey.as_deref() == Some(pubkey))
}

/// Find a mutable slot by its current client pubkey.
pub fn find_slot_by_pubkey_mut<'a>(slots: &'a mut [ConnectSlot], pubkey: &str) -> Option<&'a mut ConnectSlot> {
    slots.iter_mut().find(|s| s.current_pubkey.as_deref() == Some(pubkey))
}

/// Find a slot by its secret using constant-time comparison.
/// Always iterates all slots to prevent timing-based slot identification.
/// Returns the first matching slot (lowest index).
pub fn find_slot_by_secret<'a>(slots: &'a [ConnectSlot], secret: &str) -> Option<&'a ConnectSlot> {
    let mut matched: Option<usize> = None;
    for (i, slot) in slots.iter().enumerate() {
        if constant_time_eq_str(&slot.secret, secret) && matched.is_none() {
            matched = Some(i);
        }
    }
    matched.map(|i| &slots[i])
}

/// Find a mutable slot by its secret using constant-time comparison.
/// Always iterates all slots to prevent timing-based slot identification.
/// Returns the first matching slot (lowest index).
pub fn find_slot_by_secret_mut<'a>(slots: &'a mut [ConnectSlot], secret: &str) -> Option<&'a mut ConnectSlot> {
    let mut matched: Option<usize> = None;
    for (i, slot) in slots.iter().enumerate() {
        if constant_time_eq_str(&slot.secret, secret) && matched.is_none() {
            matched = Some(i);
        }
    }
    matched.map(move |i| &mut slots[i])
}

/// Find the next available slot index (0-15). Returns None if all 16 are occupied.
pub fn next_slot_index(slots: &[ConnectSlot]) -> Option<u8> {
    for i in 0..MAX_CONNECT_SLOTS {
        if !slots.iter().any(|s| s.slot_index == i) {
            return Some(i);
        }
    }
    None
}

/// Create a redacted copy of a slot (secret replaced with empty string).
pub fn redact_slot(slot: &ConnectSlot) -> ConnectSlot {
    ConnectSlot {
        secret: String::new(),
        ..slot.clone()
    }
}

/// Constant-time string equality (prevents timing attacks on secret comparison).
fn constant_time_eq_str(a: &str, b: &str) -> bool {
    let a = a.as_bytes();
    let b = b.as_bytes();
    if a.len() != b.len() {
        return false;
    }
    let mut diff = 0u8;
    for (x, y) in a.iter().zip(b.iter()) {
        diff |= x ^ y;
    }
    diff == 0
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_pubkey(c: char) -> String {
        c.to_string().repeat(64)
    }

    fn sample_policy(c: char) -> ClientPolicy {
        ClientPolicy {
            client_pubkey: sample_pubkey(c),
            label: format!("Client {c}"),
            allowed_methods: vec!["sign_event".into()],
            allowed_kinds: vec![1, 7],
            auto_approve: true,
        }
    }

    // --- Serde roundtrip ---

    #[test]
    fn serde_roundtrip() {
        let policy = sample_policy('a');
        let json = serde_json::to_string(&policy).unwrap();
        let decoded: ClientPolicy = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.client_pubkey, policy.client_pubkey);
        assert_eq!(decoded.label, "Client a");
        assert_eq!(decoded.allowed_kinds, vec![1, 7]);
        assert!(decoded.auto_approve);
    }

    #[test]
    fn serde_defaults() {
        // Minimal JSON with only the required field.
        let json = r#"{"client_pubkey":"aa"}"#;
        let policy: ClientPolicy = serde_json::from_str(json).unwrap();
        assert_eq!(policy.client_pubkey, "aa");
        assert_eq!(policy.label, "");
        assert!(policy.allowed_methods.is_empty());
        assert!(policy.allowed_kinds.is_empty());
        assert!(!policy.auto_approve);
    }

    #[test]
    fn serde_vec_roundtrip() {
        let policies = vec![sample_policy('a'), sample_policy('b')];
        let json = serde_json::to_string(&policies).unwrap();
        let decoded: Vec<ClientPolicy> = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.len(), 2);
        assert_eq!(decoded[0].label, "Client a");
        assert_eq!(decoded[1].label, "Client b");
    }

    // --- TOFU defaults ---

    #[test]
    fn tofu_policy_has_correct_defaults() {
        let policy = make_tofu_policy(&sample_pubkey('x'));
        assert!(policy.auto_approve);
        assert!(policy.label.is_empty());
        assert!(policy.allowed_kinds.is_empty());
        assert_eq!(policy.allowed_methods.len(), TOFU_SAFE_METHODS.len());
        for method in TOFU_SAFE_METHODS {
            assert!(policy.allowed_methods.contains(&method.to_string()));
        }
    }

    #[test]
    fn tofu_safe_methods_includes_essentials() {
        assert!(TOFU_SAFE_METHODS.contains(&"sign_event"));
        assert!(TOFU_SAFE_METHODS.contains(&"nip44_encrypt"));
        assert!(TOFU_SAFE_METHODS.contains(&"nip44_decrypt"));
        assert!(TOFU_SAFE_METHODS.contains(&"get_public_key"));
    }

    // --- Connect-safe methods ---

    #[test]
    fn connect_safe_methods_excludes_signing() {
        assert!(!CONNECT_SAFE_METHODS.contains(&"sign_event"));
    }

    #[test]
    fn connect_safe_methods_includes_crypto() {
        assert!(CONNECT_SAFE_METHODS.contains(&"nip44_encrypt"));
        assert!(CONNECT_SAFE_METHODS.contains(&"nip44_decrypt"));
        assert!(CONNECT_SAFE_METHODS.contains(&"nip04_encrypt"));
        assert!(CONNECT_SAFE_METHODS.contains(&"nip04_decrypt"));
        assert!(CONNECT_SAFE_METHODS.contains(&"get_public_key"));
    }

    #[test]
    fn connect_safe_is_subset_of_tofu_safe() {
        for method in CONNECT_SAFE_METHODS {
            assert!(TOFU_SAFE_METHODS.contains(method),
                "{} is in CONNECT_SAFE but not TOFU_SAFE", method);
        }
    }

    #[test]
    fn connect_policy_has_correct_defaults() {
        let policy = make_connect_policy(&sample_pubkey('x'));
        assert!(policy.auto_approve);
        assert!(policy.label.is_empty());
        assert!(policy.allowed_kinds.is_empty());
        assert_eq!(policy.allowed_methods.len(), CONNECT_SAFE_METHODS.len());
        assert!(!policy.allowed_methods.contains(&"sign_event".to_string()));
        for method in CONNECT_SAFE_METHODS {
            assert!(policy.allowed_methods.contains(&method.to_string()));
        }
    }

    // --- Find ---

    #[test]
    fn find_existing_policy() {
        let policies = vec![sample_policy('a'), sample_policy('b')];
        let found = find_policy(&policies, &sample_pubkey('b'));
        assert!(found.is_some());
        assert_eq!(found.unwrap().label, "Client b");
    }

    #[test]
    fn find_missing_policy() {
        let policies = vec![sample_policy('a')];
        assert!(find_policy(&policies, &sample_pubkey('z')).is_none());
    }

    #[test]
    fn find_in_empty_list() {
        let policies: Vec<ClientPolicy> = vec![];
        assert!(find_policy(&policies, &sample_pubkey('a')).is_none());
    }

    // --- Revoke ---

    #[test]
    fn revoke_existing_policy() {
        let mut policies = vec![sample_policy('a'), sample_policy('b'), sample_policy('c')];
        assert!(revoke_policy(&mut policies, &sample_pubkey('b')));
        assert_eq!(policies.len(), 2);
        assert!(find_policy(&policies, &sample_pubkey('b')).is_none());
        // Others untouched.
        assert!(find_policy(&policies, &sample_pubkey('a')).is_some());
        assert!(find_policy(&policies, &sample_pubkey('c')).is_some());
    }

    #[test]
    fn revoke_missing_policy() {
        let mut policies = vec![sample_policy('a')];
        assert!(!revoke_policy(&mut policies, &sample_pubkey('z')));
        assert_eq!(policies.len(), 1);
    }

    #[test]
    fn revoke_from_empty_list() {
        let mut policies: Vec<ClientPolicy> = vec![];
        assert!(!revoke_policy(&mut policies, &sample_pubkey('a')));
    }

    // --- Upsert ---

    #[test]
    fn upsert_adds_new_policy() {
        let mut policies = vec![sample_policy('a')];
        upsert_policy(&mut policies, sample_policy('b'));
        assert_eq!(policies.len(), 2);
        assert_eq!(find_policy(&policies, &sample_pubkey('b')).unwrap().label, "Client b");
    }

    #[test]
    fn upsert_replaces_existing_policy() {
        let mut policies = vec![sample_policy('a')];
        let mut updated = sample_policy('a');
        updated.label = "Updated".into();
        updated.auto_approve = false;
        upsert_policy(&mut policies, updated);
        assert_eq!(policies.len(), 1);
        let found = find_policy(&policies, &sample_pubkey('a')).unwrap();
        assert_eq!(found.label, "Updated");
        assert!(!found.auto_approve);
    }

    #[test]
    fn upsert_into_empty_list() {
        let mut policies: Vec<ClientPolicy> = vec![];
        upsert_policy(&mut policies, sample_policy('a'));
        assert_eq!(policies.len(), 1);
    }

    // --- Approval tier ---

    #[test]
    fn approval_tier_values_are_distinct() {
        assert_ne!(ApprovalTier::AutoApprove, ApprovalTier::ButtonRequired);
        assert_ne!(ApprovalTier::AutoApprove, ApprovalTier::OledNotify);
        assert_ne!(ApprovalTier::OledNotify, ApprovalTier::ButtonRequired);
    }

    // --- ConnectSlot ---

    fn sample_slot(index: u8, label: &str) -> ConnectSlot {
        ConnectSlot {
            slot_index: index,
            label: label.to_string(),
            secret: "ab".repeat(32),
            current_pubkey: None,
            allowed_methods: CONNECT_SAFE_METHODS.iter().map(|s| s.to_string()).collect(),
            allowed_kinds: vec![],
            auto_approve: true,
            signing_approved: false,
        }
    }

    #[test]
    fn connect_slot_serde_roundtrip() {
        let slot = sample_slot(0, "nostrudel desktop");
        let json = serde_json::to_string(&slot).unwrap();
        let decoded: ConnectSlot = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.slot_index, 0);
        assert_eq!(decoded.label, "nostrudel desktop");
        assert_eq!(decoded.secret, "ab".repeat(32));
        assert!(decoded.current_pubkey.is_none());
        assert!(!decoded.signing_approved);
    }

    #[test]
    fn connect_slot_serde_with_pubkey() {
        let mut slot = sample_slot(3, "Bark laptop");
        slot.current_pubkey = Some(sample_pubkey('c'));
        slot.signing_approved = true;
        let json = serde_json::to_string(&slot).unwrap();
        let decoded: ConnectSlot = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.current_pubkey, Some(sample_pubkey('c')));
        assert!(decoded.signing_approved);
    }

    #[test]
    fn connect_slot_vec_serde_roundtrip() {
        let slots = vec![
            sample_slot(0, "nostrudel desktop"),
            sample_slot(1, "Bark laptop"),
        ];
        let json = serde_json::to_string(&slots).unwrap();
        let decoded: Vec<ConnectSlot> = serde_json::from_str(&json).unwrap();
        assert_eq!(decoded.len(), 2);
        assert_eq!(decoded[0].label, "nostrudel desktop");
        assert_eq!(decoded[1].slot_index, 1);
    }

    #[test]
    fn connect_slot_defaults() {
        let json = r#"{"slot_index":0,"label":"test","secret":"aa"}"#;
        let slot: ConnectSlot = serde_json::from_str(json).unwrap();
        assert!(slot.current_pubkey.is_none());
        assert!(slot.allowed_methods.is_empty());
        assert!(slot.allowed_kinds.is_empty());
        assert!(!slot.auto_approve);
        assert!(!slot.signing_approved);
    }

    #[test]
    fn find_slot_by_pubkey_found() {
        let mut slot = sample_slot(0, "test");
        slot.current_pubkey = Some(sample_pubkey('a'));
        let slots = vec![slot, sample_slot(1, "other")];
        let found = find_slot_by_pubkey(&slots, &sample_pubkey('a'));
        assert!(found.is_some());
        assert_eq!(found.unwrap().label, "test");
    }

    #[test]
    fn find_slot_by_pubkey_not_found() {
        let slots = vec![sample_slot(0, "test")];
        assert!(find_slot_by_pubkey(&slots, &sample_pubkey('z')).is_none());
    }

    #[test]
    fn find_slot_by_pubkey_empty() {
        let slots: Vec<ConnectSlot> = vec![];
        assert!(find_slot_by_pubkey(&slots, &sample_pubkey('a')).is_none());
    }

    #[test]
    fn find_slot_by_secret_found() {
        let slots = vec![
            sample_slot(0, "first"),
            sample_slot(1, "second"),
        ];
        // sample_slot uses "ab".repeat(32) for secret
        let found = find_slot_by_secret(&slots, &"ab".repeat(32));
        assert!(found.is_some());
        // Both have same secret in this test -- first match wins
        assert_eq!(found.unwrap().slot_index, 0);
    }

    #[test]
    fn find_slot_by_secret_not_found() {
        let slots = vec![sample_slot(0, "test")];
        assert!(find_slot_by_secret(&slots, &"ff".repeat(32)).is_none());
    }

    #[test]
    fn next_slot_index_empty() {
        let slots: Vec<ConnectSlot> = vec![];
        assert_eq!(next_slot_index(&slots), Some(0));
    }

    #[test]
    fn next_slot_index_gaps() {
        let slots = vec![sample_slot(0, "a"), sample_slot(2, "c")];
        assert_eq!(next_slot_index(&slots), Some(1));
    }

    #[test]
    fn next_slot_index_full() {
        let slots: Vec<ConnectSlot> = (0..16).map(|i| sample_slot(i, "x")).collect();
        assert_eq!(next_slot_index(&slots), None);
    }

    #[test]
    fn redact_slot_hides_secret() {
        let slot = sample_slot(0, "test");
        let redacted = redact_slot(&slot);
        assert!(redacted.secret.is_empty());
        assert_eq!(redacted.label, "test");
        assert_eq!(redacted.slot_index, 0);
    }
}
